import { useEffect, useMemo, useRef, useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  arrayMove,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Download, Eye, Plus, Check, ChevronsUpDown, ChevronDown, Upload, FileText, Trash2, Search, Pencil, RefreshCw, GripVertical, History as HistoryIcon, User as UserIcon, MoreHorizontal, Truck, Package, Calendar as CalendarIcon, CheckCircle } from "lucide-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { format } from "date-fns";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { insertTrailerSchema, type InsertTrailer, type Trailer, type TrailerDocument } from "@shared/schema";
import {
  DOCUMENT_CATEGORIES,
  DOCUMENT_TYPE_CATALOG,
  type DocumentCategory,
  type DocumentStatus,
} from "@shared/document-types";
import { z } from "zod";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { formatCurrency } from "@/lib/currency";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/hooks/useAuth";
import { useUpload } from "@/hooks/use-upload";

const assetFormSchema = insertTrailerSchema.extend({
  allocationType: z.enum(["open", "specific"]).default("open"),
  investorId: z.string().optional(),
}).superRefine((data, ctx) => {
  if (data.allocationType === "specific" && !data.investorId) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: "Investor is required when allocation type is 'specific'",
      path: ["investorId"],
    });
  }
});

type AssetFormData = z.infer<typeof assetFormSchema>;

export default function Assets() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingTrailer, setEditingTrailer] = useState<any | null>(null);
  const [detailsDialogOpen, setDetailsDialogOpen] = useState(false);
  const [selectedTrailer, setSelectedTrailer] = useState<any>(null);
  const [allocationType, setAllocationType] = useState<"open" | "specific">("open");
  const [investorComboOpen, setInvestorComboOpen] = useState(false);
  const isEditing = !!editingTrailer;
  // Trailer list filters (year/make/vehicleUse + free text against vin/titleNumber/trailerId)
  const [filterSearch, setFilterSearch] = useState("");
  const [filterYear, setFilterYear] = useState<string>("all");
  const [filterMake, setFilterMake] = useState<string>("all");
  const [filterVehicleUse, setFilterVehicleUse] = useState<string>("all");
  const { toast } = useToast();
  
  const { data: trailers, isLoading } = useQuery<any[]>({
    queryKey: ["/api/trailers"],
  });

  const { data: investors } = useQuery({
    queryKey: ["/api/investors"],
  });

  const form = useForm<AssetFormData>({
    resolver: zodResolver(assetFormSchema),
    defaultValues: {
      trailerId: "", // Will be auto-generated by backend
      trailerType: "Seco",
      model: "",
      purchaseValue: "",
      purchaseDate: new Date().toISOString().split('T')[0],
      currentValue: "",
      status: "stock",
      depreciationRate: "0.05",
      location: "",
      latitude: "",
      longitude: "",
      totalShares: 1,
      allocationType: "open",
      investorId: "",
      vin: "",
      year: undefined,
      make: "",
      body: "",
      weightLbs: undefined,
      titleNumber: "",
      vehicleUse: undefined,
      titleDate: "",
      imageData: "",
    },
  });

  const closeDialog = () => {
    setDialogOpen(false);
    setEditingTrailer(null);
    setAllocationType("open");
    form.reset();
  };

  const createTrailerMutation = useMutation({
    mutationFn: async (data: InsertTrailer) => {
      return await apiRequest("POST", "/api/trailers", data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers"] });
      toast({
        title: t('assets.successTitle'),
        description: t('assets.successDescription'),
      });
      closeDialog();
    },
    onError: (error: any) => {
      // Check if we have field-specific errors from the backend
      if (error.errors && typeof error.errors === 'object') {
        // Set errors on specific fields with translated messages
        Object.entries(error.errors).forEach(([field, message]) => {
          // Check if the message is a translation key
          const translatedMessage = t(`assets.${message}`, { defaultValue: message as string });
          form.setError(field as any, {
            type: 'manual',
            message: translatedMessage,
          });
        });
        
        // Show toast with translated main error message
        const translatedError = t(`assets.${error.message}`, { defaultValue: t('assets.errorDescription') });
        toast({
          title: t('assets.errorTitle'),
          description: translatedError,
          variant: "destructive",
        });
      } else {
        // Generic error handling
        const translatedError = error.message ? t(`assets.${error.message}`, { defaultValue: error.message }) : t('assets.errorDescription');
        toast({
          title: t('assets.errorTitle'),
          description: translatedError,
          variant: "destructive",
        });
      }
    },
  });

  const updateTrailerMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<InsertTrailer> }) => {
      const res = await apiRequest("PATCH", `/api/trailers/${id}`, data);
      return (await res.json()) as Trailer;
    },
    onSuccess: (updated: Trailer) => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers"] });
      // The PATCH endpoint writes a new audit log entry, so refresh the
      // History tab's cached query for this trailer too — otherwise the
      // tab keeps showing stale data because audit-log queries reuse the
      // global Infinity staleTime.
      queryClient.invalidateQueries({
        queryKey: ["/api/trailers", updated.id, "audit-logs"],
      });
      toast({
        title: t('assets.editSuccessTitle', 'Ativo atualizado'),
        description: t('assets.editSuccessDescription', 'As alterações foram salvas com sucesso.'),
      });
      // Keep the details dialog in sync if it is open for this trailer.
      if (selectedTrailer && selectedTrailer.id === updated.id) {
        setSelectedTrailer({ ...selectedTrailer, ...updated });
      }
      closeDialog();
    },
    onError: (error: any) => {
      if (error.errors && typeof error.errors === 'object') {
        Object.entries(error.errors).forEach(([field, message]) => {
          const translatedMessage = t(`assets.${message}`, { defaultValue: message as string });
          form.setError(field as any, { type: 'manual', message: translatedMessage });
        });
        const translatedError = t(`assets.${error.message}`, { defaultValue: t('assets.errorDescription') });
        toast({ title: t('assets.errorTitle'), description: translatedError, variant: "destructive" });
      } else {
        const translatedError = error.message ? t(`assets.${error.message}`, { defaultValue: error.message }) : t('assets.errorDescription');
        toast({ title: t('assets.errorTitle'), description: translatedError, variant: "destructive" });
      }
    },
  });

  const onSubmit = (data: AssetFormData) => {
    // Normalize: convert "" → undefined for every optional vehicle/location
    // field so the backend stores NULL rather than persisting empty strings
    // (which would defeat indexes and downstream filters).
    const optionalStringFields = [
      "latitude",
      "longitude",
      "vin",
      "make",
      "body",
      "titleNumber",
      "vehicleUse",
      "titleDate",
      "imageData",
    ] as const;

    const cleanedData: Record<string, any> = { ...data };
    for (const key of optionalStringFields) {
      if (cleanedData[key] === "" || cleanedData[key] === null) {
        cleanedData[key] = undefined;
      }
    }
    // Numeric optionals: drop empty / NaN values so Zod treats them as missing.
    for (const key of ["year", "weightLbs"] as const) {
      if (cleanedData[key] === "" || cleanedData[key] === null || Number.isNaN(cleanedData[key])) {
        cleanedData[key] = undefined;
      }
    }

    if (isEditing && editingTrailer) {
      // PATCH: drop allocation-only and server-managed fields that don't
      // belong to a partial trailer update.
      const { allocationType: _a, investorId: _i, trailerId: _tid, ...patchData } = cleanedData;
      updateTrailerMutation.mutate({ id: editingTrailer.id, data: patchData as Partial<InsertTrailer> });
      return;
    }

    cleanedData.allocationType = data.allocationType || "open";
    cleanedData.investorId = data.allocationType === "specific" ? data.investorId : undefined;

    createTrailerMutation.mutate(cleanedData as any);
  };

  const openEditDialog = (trailer: any) => {
    setEditingTrailer(trailer);
    setAllocationType("open"); // hidden in edit mode anyway
    form.reset({
      trailerId: trailer.trailerId ?? "",
      trailerType: trailer.trailerType ?? "Seco",
      model: trailer.model ?? "",
      purchaseValue: trailer.purchaseValue ?? "",
      purchaseDate: trailer.purchaseDate
        ? new Date(trailer.purchaseDate).toISOString().split('T')[0]
        : new Date().toISOString().split('T')[0],
      currentValue: trailer.currentValue ?? "",
      status: trailer.status ?? "stock",
      depreciationRate: trailer.depreciationRate ?? "0.05",
      location: trailer.location ?? "",
      latitude: trailer.latitude ?? "",
      longitude: trailer.longitude ?? "",
      totalShares: trailer.totalShares ?? 1,
      allocationType: "open",
      investorId: "",
      vin: trailer.vin ?? "",
      year: trailer.year ?? undefined,
      make: trailer.make ?? "",
      body: trailer.body ?? "",
      weightLbs: trailer.weightLbs ?? undefined,
      titleNumber: trailer.titleNumber ?? "",
      vehicleUse:
        trailer.vehicleUse === "PRIVATE" || trailer.vehicleUse === "COMMERCIAL"
          ? trailer.vehicleUse
          : undefined,
      titleDate: trailer.titleDate
        ? new Date(trailer.titleDate).toISOString().split('T')[0]
        : "",
      imageData: trailer.imageData ?? "",
    } as AssetFormData);
    setDialogOpen(true);
  };

  const onFormError = (errors: any) => {
    // Show toast with validation errors
    const errorMessages = Object.entries(errors)
      .map(([field, error]: [string, any]) => `${field}: ${error.message}`)
      .join('\n');
    
    toast({
      title: t('assets.validationError', 'Erros de validação'),
      description: errorMessages,
      variant: "destructive",
    });
  };

  // Distinct year/make/vehicleUse values for filter dropdowns
  const filterOptions = useMemo(() => {
    const list = trailers ?? [];
    const years = Array.from(new Set(list.map((t: any) => t.year).filter((v: any) => v != null))).sort((a: any, b: any) => b - a);
    const makes = Array.from(new Set(list.map((t: any) => t.make).filter(Boolean))).sort() as string[];
    const uses = Array.from(new Set(list.map((t: any) => t.vehicleUse).filter(Boolean))).sort() as string[];
    return { years, makes, uses };
  }, [trailers]);

  const filteredTrailers = useMemo(() => {
    const list = trailers ?? [];
    const term = filterSearch.trim().toLowerCase();
    return list.filter((trailer: any) => {
      if (filterYear !== "all" && String(trailer.year ?? "") !== filterYear) return false;
      if (filterMake !== "all" && (trailer.make ?? "") !== filterMake) return false;
      if (filterVehicleUse !== "all" && (trailer.vehicleUse ?? "") !== filterVehicleUse) return false;
      if (term) {
        const hay = `${trailer.trailerId ?? ""} ${trailer.vin ?? ""} ${trailer.titleNumber ?? ""}`.toLowerCase();
        if (!hay.includes(term)) return false;
      }
      return true;
    });
  }, [trailers, filterYear, filterMake, filterVehicleUse, filterSearch]);

  const getStatusBadge = (status: string) => {
    const pillBase = "text-white font-medium border-none rounded-sm px-2.5 py-0.5 text-xs uppercase tracking-wide";
    const variants: Record<string, { variant: "default" | "secondary" | "destructive" | "outline"; label: string; className: string }> = {
      active: {
        variant: "default",
        label: t('assets.statusActive'),
        className: `bg-emerald-500 hover:bg-emerald-500/90 ${pillBase}`,
      },
      rented: {
        variant: "default",
        label: t('assets.statusRented', 'Em Locação'),
        className: `bg-emerald-500 hover:bg-emerald-500/90 ${pillBase}`,
      },
      stock: {
        variant: "secondary",
        label: t('assets.statusStock'),
        className: `bg-blue-500 hover:bg-blue-500/90 ${pillBase}`,
      },
      maintenance: {
        variant: "outline",
        label: t('assets.statusMaintenance'),
        className: `bg-amber-500 hover:bg-amber-500/90 ${pillBase}`,
      },
      expired: {
        variant: "destructive",
        label: t('assets.statusExpired'),
        className: `bg-red-500 hover:bg-red-500/90 ${pillBase}`,
      },
      sold: {
        variant: "default",
        label: t('assets.statusSold', 'Vendido'),
        className: `bg-violet-500 hover:bg-violet-500/90 ${pillBase}`,
      },
    };
    return variants[status] || variants.stock;
  };

  const getTrafficLight = (purchaseDate: string) => {
    const purchase = new Date(purchaseDate);
    const now = new Date();
    const monthsDiff = (now.getTime() - purchase.getTime()) / (1000 * 60 * 60 * 24 * 30);
    
    if (monthsDiff < 12) return "bg-green-500";
    if (monthsDiff < 24) return "bg-yellow-500";
    return "bg-red-500";
  };

  const handleExport = () => {
    if (!trailers || trailers.length === 0) {
      toast({
        title: t('assets.noDataToExport'),
        description: t('assets.noAssetsRegistered'),
        variant: "destructive",
      });
      return;
    }

    const statusTranslations: Record<string, string> = {
      stock: t('assets.statusStock'),
      active: t('assets.statusActive'),
      maintenance: t('assets.statusMaintenance'),
      expired: t('assets.statusExpired'),
    };

    const headers = [
      t('assets.trailerId'),
      t('assets.status'),
      t('assets.sharesSold'),
      t('assets.totalShares'),
      t('assets.sharesAvailable'),
      t('assets.purchaseValue'),
      t('assets.currentValue'),
      t('assets.purchaseDate'),
      t('assets.depreciationRate'),
      t('assets.location'),
      t('assets.latitude'),
      t('assets.longitude')
    ];

    // Função para formatar valores monetários no padrão brasileiro
    const formatCurrency = (value: string | number) => {
      const num = parseFloat(String(value));
      const formatted = num.toLocaleString('pt-BR', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      });
      return `$ ${formatted}`;
    };

    const csvData = trailers.map((trailer: any) => [
      trailer.trailerId,
      statusTranslations[trailer.status] || trailer.status,
      trailer.soldShares || 0,
      trailer.totalShares || 1,
      (trailer.totalShares || 1) - (trailer.soldShares || 0),
      formatCurrency(trailer.purchaseValue),
      formatCurrency(trailer.currentValue),
      format(new Date(trailer.purchaseDate), "dd/MM/yyyy"),
      trailer.depreciationRate || "0",
      trailer.location || "",
      trailer.latitude || "",
      trailer.longitude || "",
    ]);

    const csvRows = [
      headers.join(";"),
      ...csvData.map((row: any[]) => 
        row.map((cell: any) => {
          const cellStr = String(cell);
          if (cellStr.includes(";") || cellStr.includes(",") || cellStr.includes('"') || cellStr.includes("\n")) {
            return `"${cellStr.replace(/"/g, '""')}"`;
          }
          return cellStr;
        }).join(";")
      )
    ];

    const BOM = "\uFEFF";
    const csvContent = BOM + csvRows.join("\r\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    
    link.setAttribute("href", url);
    link.setAttribute("download", `ativos_opus_rental_${format(new Date(), "yyyy-MM-dd")}.csv`);
    link.style.visibility = "hidden";
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast({
      title: t('assets.exportSuccess'),
      description: t('assets.exportDescription'),
    });
  };

  if (isLoading) {
    return (
      <div className="p-6">
        <Skeleton className="h-96" />
      </div>
    );
  }

  const totalAssets = trailers?.length || 0;
  const stockCount = trailers?.filter((t: Trailer) => t.status === 'stock').length || 0;
  const rentedCount = trailers?.filter((t: Trailer) => t.status === 'rented').length || 0;
  const soldCount = trailers?.filter((t: Trailer) => t.status === 'sold').length || 0;

  return (
    <div className="bg-background p-3 sm:p-4 md:p-6 lg:p-8 space-y-4 sm:space-y-6 lg:space-y-8" data-testid="page-assets">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground tracking-tight">{t('assets.title')}</h1>
          <p className="text-sm text-muted-foreground mt-1">{t('assets.subtitle')}</p>
        </div>
        <div className="flex flex-wrap gap-3 w-full sm:w-auto">
          <Button
            className="bg-accent hover:bg-accent/90 text-accent-foreground shadow-sm font-medium"
            data-testid="button-new-asset"
            onClick={() => {
              setEditingTrailer(null);
              setAllocationType("open");
              form.reset();
              setDialogOpen(true);
            }}
          >
            <Plus className="mr-2 h-4 w-4" />
            {t('assets.newAsset')}
          </Button>
          <Button
            variant="outline"
            data-testid="button-export"
            onClick={handleExport}
          >
            <Download className="mr-2 h-4 w-4" />
            {t('assets.export')}
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-card border border-border shadow-sm rounded-xl overflow-hidden" data-testid="card-stat-total">
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-muted-foreground mb-1">{t('assets.statTotal', 'Total de Ativos')}</p>
              <h3 className="text-2xl font-bold text-foreground" data-testid="text-stat-total">{totalAssets}</h3>
            </div>
            <div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center">
              <Truck className="h-5 w-5 text-muted-foreground" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border border-border shadow-sm rounded-xl overflow-hidden" data-testid="card-stat-stock">
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-muted-foreground mb-1">{t('assets.statStock', 'Em Estoque')}</p>
              <h3 className="text-2xl font-bold text-blue-600 dark:text-blue-400" data-testid="text-stat-stock">{stockCount}</h3>
            </div>
            <div className="h-10 w-10 rounded-full bg-blue-50 dark:bg-blue-500/15 flex items-center justify-center">
              <Package className="h-5 w-5 text-blue-600 dark:text-blue-400" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border border-border shadow-sm rounded-xl overflow-hidden" data-testid="card-stat-rented">
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-muted-foreground mb-1">{t('assets.statRented', 'Em Locação')}</p>
              <h3 className="text-2xl font-bold text-emerald-600 dark:text-emerald-400" data-testid="text-stat-rented">{rentedCount}</h3>
            </div>
            <div className="h-10 w-10 rounded-full bg-emerald-50 dark:bg-emerald-500/15 flex items-center justify-center">
              <CalendarIcon className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border border-border shadow-sm rounded-xl overflow-hidden" data-testid="card-stat-sold">
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-muted-foreground mb-1">{t('assets.statSold', 'Vendidos')}</p>
              <h3 className="text-2xl font-bold text-violet-600 dark:text-violet-400" data-testid="text-stat-sold">{soldCount}</h3>
            </div>
            <div className="h-10 w-10 rounded-full bg-violet-50 dark:bg-violet-500/15 flex items-center justify-center">
              <CheckCircle className="h-5 w-5 text-violet-600 dark:text-violet-400" />
            </div>
          </CardContent>
        </Card>
      </div>

      <Dialog
        open={dialogOpen}
        onOpenChange={(open) => {
          if (!open) closeDialog();
          else setDialogOpen(true);
        }}
      >
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle data-testid="text-asset-dialog-title">
              {isEditing
                ? t('assets.editAssetDialog', 'Editar Ativo')
                : t('assets.newAssetDialog')}
            </DialogTitle>
            <DialogDescription>
              {isEditing
                ? t('assets.editAssetDescription', 'Atualize as informações do veículo. Apenas os campos modificados serão salvos.')
                : t('assets.newAssetDescription')}
            </DialogDescription>
          </DialogHeader>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit, onFormError)} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="trailerType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.trailerType')}</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-trailer-type">
                            <SelectValue placeholder={t('assets.selectTrailerType')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Seco">{t('assets.trailerTypeSeco')}</SelectItem>
                          <SelectItem value="Climatizado">{t('assets.trailerTypeClimatizado')}</SelectItem>
                          <SelectItem value="Lonado">{t('assets.trailerTypeLonado')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                      {!isEditing && (
                        <p className="text-xs text-muted-foreground mt-1">
                          {t('assets.autoIdHint', 'ID será gerado automaticamente (ex: TRS001, TRC002, TRL003)')}
                        </p>
                      )}
                      {isEditing && editingTrailer?.trailerId && (
                        <p className="text-xs text-muted-foreground mt-1" data-testid="text-edit-trailer-id">
                          {t('assets.trailerId')}: <span className="font-mono">{editingTrailer.trailerId}</span>
                        </p>
                      )}
                    </FormItem>
                  )}
                />

                {!isEditing && (
                  <FormField
                    control={form.control}
                    name="allocationType"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.allocationType')}</FormLabel>
                        <Select
                          onValueChange={(value) => {
                            field.onChange(value);
                            setAllocationType(value as "open" | "specific");
                          }}
                          defaultValue={field.value}
                        >
                          <FormControl>
                            <SelectTrigger data-testid="select-allocation-type">
                              <SelectValue placeholder={t('assets.selectAllocationType')} />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="open">{t('assets.allocationTypeOpen')}</SelectItem>
                            <SelectItem value="specific">{t('assets.allocationTypeSpecific')}</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                        <p className="text-xs text-muted-foreground mt-1">
                          {allocationType === "open" ? t('assets.allocationOpenHint') : t('assets.allocationSpecificHint')}
                        </p>
                      </FormItem>
                    )}
                  />
                )}
              </div>

              {!isEditing && allocationType === "specific" && (
                <div className="grid grid-cols-1 gap-4">
                  <FormField
                    control={form.control}
                    name="investorId"
                    render={({ field }) => (
                      <FormItem className="flex flex-col">
                        <FormLabel>{t('assets.selectInvestor')}</FormLabel>
                        <Popover open={investorComboOpen} onOpenChange={setInvestorComboOpen}>
                          <PopoverTrigger asChild>
                            <FormControl>
                              <Button
                                variant="outline"
                                role="combobox"
                                aria-expanded={investorComboOpen}
                                className="w-full justify-between"
                                data-testid="button-select-investor"
                              >
                                {field.value
                                  ? investors?.find((investor: any) => investor.id === field.value)
                                    ? `${investors.find((inv: any) => inv.id === field.value).firstName} ${investors.find((inv: any) => inv.id === field.value).lastName} (${investors.find((inv: any) => inv.id === field.value).email})`
                                    : t('assets.selectInvestorPlaceholder')
                                  : t('assets.selectInvestorPlaceholder')}
                                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                              </Button>
                            </FormControl>
                          </PopoverTrigger>
                          <PopoverContent className="w-[400px] p-0">
                            <Command>
                              <CommandInput placeholder={t('assets.searchInvestor')} />
                              <CommandList>
                                <CommandEmpty>{t('assets.noInvestorsFound')}</CommandEmpty>
                                <CommandGroup>
                                  {investors?.map((investor: any) => {
                                    const searchValue = `${investor.firstName} ${investor.lastName} ${investor.email}`.toLowerCase();
                                    return (
                                      <CommandItem
                                        key={investor.id}
                                        value={searchValue}
                                        onSelect={() => {
                                          form.setValue("investorId", investor.id);
                                          setInvestorComboOpen(false);
                                        }}
                                      >
                                        <Check
                                          className={`mr-2 h-4 w-4 ${
                                            field.value === investor.id ? "opacity-100" : "opacity-0"
                                          }`}
                                        />
                                        {investor.firstName} {investor.lastName} ({investor.email})
                                      </CommandItem>
                                    );
                                  })}
                                </CommandGroup>
                              </CommandList>
                            </Command>
                          </PopoverContent>
                        </Popover>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              )}

              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="model"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.model')}</FormLabel>
                      <FormControl>
                        <Input placeholder="Dry Van 53ft" {...field} data-testid="input-model" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="status"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.status')}</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-status">
                            <SelectValue placeholder={t('assets.selectStatus')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="stock">{t('assets.statusStock')}</SelectItem>
                          <SelectItem value="active">{t('assets.statusActive')}</SelectItem>
                          <SelectItem value="maintenance">{t('assets.statusMaintenance')}</SelectItem>
                          <SelectItem value="expired">{t('assets.statusExpired')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="purchaseValue"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.purchaseValue')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="50000.00" {...field} data-testid="input-purchase-value" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="currentValue"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.currentValue')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="50000.00" {...field} data-testid="input-current-value" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="purchaseDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.purchaseDate')}</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} data-testid="input-purchase-date" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="depreciationRate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.depreciationRate')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="0.05" {...field} data-testid="input-depreciation-rate" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="totalShares"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.totalShares')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          min="1" 
                          placeholder="1" 
                          {...field} 
                          value={field.value || 1}
                          onChange={(e) => field.onChange(parseInt(e.target.value) || 1)}
                          data-testid="input-total-shares" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="location"
                  render={({ field }) => (
                    <FormItem className="col-span-2">
                      <FormLabel>{t('assets.location')}</FormLabel>
                      <FormControl>
                        <Input placeholder="Houston, TX" {...field} value={field.value || ""} data-testid="input-location" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="latitude"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.latitude')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          step="0.0000001" 
                          placeholder="29.7604" 
                          {...field} 
                          value={field.value || ""} 
                          data-testid="input-latitude" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="longitude"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.longitude')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          step="0.0000001" 
                          placeholder="-95.3698" 
                          {...field} 
                          value={field.value || ""} 
                          data-testid="input-longitude" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              {/* Vehicle identification fields — all optional, collapsible */}
              <Collapsible className="border-t pt-2 mt-2">
                <CollapsibleTrigger
                  className="flex w-full items-center justify-between py-2 group"
                  data-testid="button-toggle-vehicle-id"
                >
                  <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">
                    {t('assets.vehicleIdSection', 'Identificação do Veículo')}
                  </h4>
                  <ChevronDown className="h-4 w-4 text-muted-foreground transition-transform group-data-[state=open]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="pt-3">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="vin"
                    render={({ field }) => (
                      <FormItem className="col-span-2">
                        <FormLabel>{t('assets.vin', 'VIN')}</FormLabel>
                        <FormControl>
                          <Input placeholder="1HGBH41JXMN109186" {...field} value={field.value ?? ""} data-testid="input-vin" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="year"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.year', 'Ano')}</FormLabel>
                        <FormControl>
                          <Input
                            type="number"
                            min="1900"
                            max="2100"
                            placeholder="2024"
                            {...field}
                            value={field.value ?? ""}
                            onChange={(e) => field.onChange(e.target.value === "" ? undefined : Number(e.target.value))}
                            data-testid="input-year"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="make"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.make', 'Marca')}</FormLabel>
                        <FormControl>
                          <Input placeholder="Great Dane" {...field} value={field.value ?? ""} data-testid="input-make" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="body"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.body', 'Carroceria')}</FormLabel>
                        <FormControl>
                          <Input placeholder="Dry Van" {...field} value={field.value ?? ""} data-testid="input-body" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="weightLbs"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.weightLbs', 'Peso (lbs)')}</FormLabel>
                        <FormControl>
                          <Input
                            type="number"
                            min="0"
                            placeholder="14000"
                            {...field}
                            value={field.value ?? ""}
                            onChange={(e) => field.onChange(e.target.value === "" ? undefined : Number(e.target.value))}
                            data-testid="input-weight-lbs"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="titleNumber"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.titleNumber', 'Nº do Título')}</FormLabel>
                        <FormControl>
                          <Input placeholder="TX1234567890" {...field} value={field.value ?? ""} data-testid="input-title-number" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="vehicleUse"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.vehicleUse', 'Uso do Veículo')}</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value ?? ""}>
                          <FormControl>
                            <SelectTrigger data-testid="select-vehicle-use">
                              <SelectValue placeholder={t('assets.selectVehicleUse', 'Selecione o uso')} />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="PRIVATE">{t('assets.vehicleUsePrivate', 'Privado')}</SelectItem>
                            <SelectItem value="COMMERCIAL">{t('assets.vehicleUseCommercial', 'Comercial')}</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="titleDate"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.titleDate', 'Data do Título')}</FormLabel>
                        <FormControl>
                          <Input type="date" {...field} value={field.value ?? ""} data-testid="input-title-date" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
                </CollapsibleContent>
              </Collapsible>

              <div className="flex justify-end gap-3 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={closeDialog}
                  data-testid="button-cancel"
                >
                  {t('assets.cancel')}
                </Button>
                <Button
                  type="submit"
                  className="bg-accent hover:bg-accent/90"
                  disabled={createTrailerMutation.isPending || updateTrailerMutation.isPending}
                  data-testid="button-submit-asset"
                >
                  {isEditing
                    ? updateTrailerMutation.isPending
                      ? t('assets.saving', 'Salvando...')
                      : t('assets.saveChanges', 'Salvar alterações')
                    : createTrailerMutation.isPending
                      ? t('assets.creating')
                      : t('assets.createAsset')}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>

      {/* Modal de Detalhes do Ativo */}
      <Dialog open={detailsDialogOpen} onOpenChange={setDetailsDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-2xl font-bold text-primary">
              {t('assets.detailsDialog')}
            </DialogTitle>
            <DialogDescription>
              {t('assets.detailsDescription')}
            </DialogDescription>
          </DialogHeader>
          
          {selectedTrailer && (
            <Tabs defaultValue="overview" className="mt-4">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="overview" data-testid="tab-overview">
                  {t('assets.tabOverview', 'Visão Geral')}
                </TabsTrigger>
                <TabsTrigger value="documents" data-testid="tab-documents">
                  {t('assets.tabDocuments', 'Documentos')}
                </TabsTrigger>
                <TabsTrigger value="history" data-testid="tab-history">
                  {t('assets.tabHistory', 'Histórico')}
                </TabsTrigger>
              </TabsList>

              <TabsContent value="overview" className="space-y-6 mt-4">
                {/* Informações Básicas */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.basicInfo')}</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.trailerId')}</label>
                      <p className="font-bold text-primary text-lg">{selectedTrailer.trailerId}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.model')}</label>
                      <p className="font-semibold">{selectedTrailer.model || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.status')}</label>
                      <div className="mt-1">
                        <Badge variant={getStatusBadge(selectedTrailer.status).variant} className="rounded-full">
                          {getStatusBadge(selectedTrailer.status).label}
                        </Badge>
                      </div>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.purchaseDate')}</label>
                      <p className="font-semibold">
                        {format(new Date(selectedTrailer.purchaseDate), "dd/MM/yyyy")}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Vehicle Identification */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.vehicleIdSection', 'Identificação do Veículo')}</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="col-span-2">
                      <label className="text-sm text-muted-foreground">{t('assets.vin', 'VIN')}</label>
                      <p className="font-mono text-sm" data-testid="text-detail-vin">{selectedTrailer.vin || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.year', 'Ano')}</label>
                      <p className="font-semibold">{selectedTrailer.year ?? "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.make', 'Marca')}</label>
                      <p className="font-semibold">{selectedTrailer.make || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.body', 'Carroceria')}</label>
                      <p className="font-semibold">{selectedTrailer.body || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.weightLbs', 'Peso (lbs)')}</label>
                      <p className="font-semibold">{selectedTrailer.weightLbs ?? "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.titleNumber', 'Nº do Título')}</label>
                      <p className="font-mono text-sm">{selectedTrailer.titleNumber || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.vehicleUse', 'Uso do Veículo')}</label>
                      <p className="font-semibold">
                        {selectedTrailer.vehicleUse === "PRIVATE"
                          ? t('assets.vehicleUsePrivate', 'Privado')
                          : selectedTrailer.vehicleUse === "COMMERCIAL"
                            ? t('assets.vehicleUseCommercial', 'Comercial')
                            : "—"}
                      </p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.titleDate', 'Data do Título')}</label>
                      <p className="font-semibold">
                        {selectedTrailer.titleDate
                          ? format(new Date(selectedTrailer.titleDate), "dd/MM/yyyy")
                          : "—"}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Informações Financeiras */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.financialInfo')}</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.purchaseValueLabel')}</label>
                      <p className="font-bold text-lg">${parseFloat(selectedTrailer.purchaseValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.currentValueLabel')}</label>
                      <p className="font-bold text-lg">${parseFloat(selectedTrailer.currentValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.depreciationRate')}</label>
                      <p className="font-semibold">{(parseFloat(selectedTrailer.depreciationRate) * 100).toFixed(1)}%</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.ageIndicator')}</label>
                      <div className="flex items-center gap-2 mt-1">
                        <div className={`w-5 h-5 ${getTrafficLight(selectedTrailer.purchaseDate)} rounded-full shadow-lg`}></div>
                        <span className="text-sm text-muted-foreground">
                          {getTrafficLight(selectedTrailer.purchaseDate) === "bg-green-500" && t('assets.lessThan1Year')}
                          {getTrafficLight(selectedTrailer.purchaseDate) === "bg-yellow-500" && t('assets.between1And2Years')}
                          {getTrafficLight(selectedTrailer.purchaseDate) === "bg-red-500" && t('assets.moreThan2Years')}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Informações de Cotas */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.sharesInfo')}</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.totalShares')}</label>
                      <p className="font-bold text-lg">{selectedTrailer.totalShares || 1}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.sharesSold')}</label>
                      <p className="font-bold text-lg">{selectedTrailer.soldShares || 0}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.sharesAvailable')}</label>
                      <p className="font-bold text-lg text-accent">
                        {(selectedTrailer.totalShares || 1) - (selectedTrailer.soldShares || 0)}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Localização */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.location')}</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.cityState')}</label>
                      <p className="font-semibold">{selectedTrailer.location || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.latitude')}</label>
                      <p className="font-mono text-sm">{selectedTrailer.latitude || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.longitude')}</label>
                      <p className="font-mono text-sm">{selectedTrailer.longitude || "—"}</p>
                    </div>
                  </div>
                </div>

                <div className="flex justify-end gap-3 pt-4">
                  <Button
                    variant="outline"
                    onClick={() => {
                      setDetailsDialogOpen(false);
                      openEditDialog(selectedTrailer);
                    }}
                    data-testid="button-edit-from-details"
                  >
                    <Pencil className="h-4 w-4 mr-2" />
                    {t('assets.editAsset', 'Editar Ativo')}
                  </Button>
                  <Button
                    onClick={() => setDetailsDialogOpen(false)}
                    className="bg-accent hover:bg-accent/90"
                    data-testid="button-close-details"
                  >
                    {t('assets.close')}
                  </Button>
                </div>
              </TabsContent>

              <TabsContent value="documents" className="mt-4">
                <TrailerDocumentsTab trailerId={selectedTrailer.id} />
              </TabsContent>

              <TabsContent value="history" className="mt-4">
                <TrailerHistoryTab trailerId={selectedTrailer.id} />
              </TabsContent>
            </Tabs>
          )}
        </DialogContent>
      </Dialog>

      {/* List Card with toolbar + table */}
      <Card className="bg-card border border-border shadow-sm rounded-xl overflow-hidden">
        {/* Toolbar / Filters */}
        <div className="p-4 md:p-5 border-b border-border flex flex-col md:flex-row gap-4 justify-between">
          <div className="relative w-full md:w-80">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              value={filterSearch}
              onChange={(e) => setFilterSearch(e.target.value)}
              placeholder={t('assets.filterSearchPlaceholder', 'ID, VIN ou nº do título')}
              className="pl-9 bg-muted/40 border-border"
              data-testid="input-filter-search"
            />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 w-full md:w-auto">
            <Select value={filterYear} onValueChange={setFilterYear}>
              <SelectTrigger className="bg-muted/40 border-border w-full sm:w-40" data-testid="select-filter-year">
                <SelectValue placeholder={t('assets.year', 'Ano')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('assets.filterAll', 'Todos os anos')}</SelectItem>
                {filterOptions.years.map((y) => (
                  <SelectItem key={String(y)} value={String(y)}>{String(y)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={filterMake} onValueChange={setFilterMake}>
              <SelectTrigger className="bg-muted/40 border-border w-full sm:w-40" data-testid="select-filter-make">
                <SelectValue placeholder={t('assets.make', 'Marca')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('assets.filterAllMakes', 'Todas as marcas')}</SelectItem>
                {filterOptions.makes.map((m: string) => (
                  <SelectItem key={m} value={m}>{m}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={filterVehicleUse} onValueChange={setFilterVehicleUse}>
              <SelectTrigger className="bg-muted/40 border-border w-full sm:w-40" data-testid="select-filter-vehicle-use">
                <SelectValue placeholder={t('assets.vehicleUse', 'Uso')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('assets.filterAllUses', 'Todos os usos')}</SelectItem>
                <SelectItem value="PRIVATE">{t('assets.vehicleUsePrivate', 'Privado')}</SelectItem>
                <SelectItem value="COMMERCIAL">{t('assets.vehicleUseCommercial', 'Comercial')}</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/40">
              <tr>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">ID</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableType')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableModel')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.status')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableShares')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableTrafficLight')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tablePurchaseValue')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableValue')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableAcquisition')}</th>
                <th className="text-left py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableLocation')}</th>
                <th className="text-right py-4 px-6 text-xs font-semibold text-muted-foreground uppercase tracking-wider">{t('assets.tableActions')}</th>
              </tr>
            </thead>
            <tbody>
              {filteredTrailers.map((trailer: Trailer & { soldShares?: number }) => {
                const statusInfo = getStatusBadge(trailer.status);
                return (
                  <tr
                    key={trailer.id}
                    className="border-b border-border hover:bg-muted/30 transition-colors"
                    data-testid={`trailer-${trailer.id}`}
                  >
                    <td className="py-4 px-6">
                      <span className="font-semibold text-foreground" data-testid={`text-trailer-id-${trailer.id}`}>{trailer.trailerId}</span>
                    </td>
                    <td className="py-4 px-6">
                      <Badge variant="outline" className="font-medium border-border">
                        {trailer.trailerType === "Seco" ? t('assets.trailerTypeSeco') :
                         trailer.trailerType === "Climatizado" ? t('assets.trailerTypeClimatizado') :
                         trailer.trailerType === "Lonado" ? t('assets.trailerTypeLonado') :
                         trailer.trailerType || "—"}
                      </Badge>
                    </td>
                    <td className="py-4 px-6">
                      <span className="text-foreground">{trailer.model || "—"}</span>
                    </td>
                    <td className="py-4 px-6">
                      <Badge className={statusInfo.className} data-testid={`badge-status-${trailer.id}`}>
                        {statusInfo.label}
                      </Badge>
                    </td>
                    <td className="py-4 px-6">
                      <span className="font-semibold text-foreground" data-testid={`text-shares-${trailer.id}`}>
                        {trailer.soldShares || 0}/{trailer.totalShares || 1}
                      </span>
                    </td>
                    <td className="py-4 px-6">
                      <div className="flex items-center gap-2">
                        <div className={`w-3 h-3 ${getTrafficLight(trailer.purchaseDate)} rounded-full`}></div>
                      </div>
                    </td>
                    <td className="py-4 px-6">
                      <span className="font-medium text-muted-foreground">
                        {formatCurrency(parseFloat(trailer.purchaseValue), user?.country)}
                      </span>
                    </td>
                    <td className="py-4 px-6">
                      <span className="font-semibold text-foreground">
                        {formatCurrency(parseFloat(trailer.currentValue), user?.country)}
                      </span>
                    </td>
                    <td className="py-4 px-6 text-muted-foreground">
                      {format(new Date(trailer.purchaseDate), "dd/MM/yyyy")}
                    </td>
                    <td className="py-4 px-6 text-muted-foreground">{trailer.location || "—"}</td>
                    <td className="py-4 px-6 text-right">
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button
                            variant="ghost"
                            className="h-8 w-8 p-0"
                            data-testid={`button-actions-${trailer.id}`}
                          >
                            <span className="sr-only">{t('assets.tableActions')}</span>
                            <MoreHorizontal className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="w-48">
                          <DropdownMenuLabel className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                            {t('assets.tableActions')}
                          </DropdownMenuLabel>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem
                            className="cursor-pointer"
                            onClick={() => {
                              setSelectedTrailer(trailer);
                              setDetailsDialogOpen(true);
                            }}
                            data-testid={`button-view-${trailer.id}`}
                          >
                            <Eye className="mr-2 h-4 w-4 text-muted-foreground" />
                            <span>{t('assets.viewDetails', 'Ver Detalhes')}</span>
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            className="cursor-pointer"
                            onClick={() => openEditDialog(trailer)}
                            data-testid={`button-edit-${trailer.id}`}
                          >
                            <Pencil className="mr-2 h-4 w-4 text-muted-foreground" />
                            <span>{t('assets.editAsset', 'Editar Ativo')}</span>
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </td>
                  </tr>
                );
              })}
              {filteredTrailers.length === 0 && (
                <tr>
                  <td colSpan={11} className="text-center py-12 text-muted-foreground">
                    {(!trailers || trailers.length === 0)
                      ? t('assets.noAssets')
                      : t('assets.noFilterResults', 'Nenhum ativo corresponde aos filtros aplicados')}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Trailer Documents — tabbed checklist UI
// ---------------------------------------------------------------------------
//
// Replaces the old free-form drag-reorder list. Documents are now bucketed
// into 4 fixed categories (Vehicle / Insurance / Contracts / Tracking) and
// inside each category every supported document_type from
// DOCUMENT_TYPE_CATALOG is rendered as a row — with or without a current
// upload — so the user always sees the full required+optional checklist.
//
// Each row owns:
//  - the current version (filename, status badge, version number, uploader)
//  - approve/reject controls (managers only) for pending documents
//  - a version-history popover listing every prior version
//  - upload / replace / delete actions
//
// "Replace" is implemented as a plain new upload because the storage layer
// auto-detects the existing chain by (trailer, document_type) and
// transparently bumps the version + flips is_current.

type EnrichedDocument = TrailerDocument & {
  uploader?: { id: string; name: string; email: string | null } | null;
  reviewer?: { id: string; name: string; email: string | null } | null;
};

type GroupedByType = Record<
  string,
  { current: EnrichedDocument | null; history: EnrichedDocument[] }
>;

function statusBadgeVariant(
  status: DocumentStatus,
): "default" | "secondary" | "destructive" {
  if (status === "approved") return "default";
  if (status === "rejected") return "destructive";
  return "secondary"; // pending
}

function TrailerDocumentsTab({ trailerId }: { trailerId: string }) {
  const { t } = useTranslation();
  const [activeTab, setActiveTab] = useState<DocumentCategory>("vehicle");

  const { data: documents, isLoading } = useQuery<EnrichedDocument[]>({
    queryKey: ["/api/trailers", trailerId, "documents"],
  });

  // Bucket every document by (category, documentType) into { current, history }.
  // `current` is the row with is_current=true (there is at most one per type).
  // `history` lists historical versions newest-first.
  const grouped = useMemo<Record<DocumentCategory, GroupedByType>>(() => {
    const byCat: Record<DocumentCategory, GroupedByType> = {
      vehicle: {},
      insurance: {},
      contract: {},
      tracking: {},
    };
    if (!documents) return byCat;

    for (const doc of documents) {
      const cat = (doc.category ?? "vehicle") as DocumentCategory;
      const type = doc.documentType ?? "other";
      // Skip rows that landed under an unknown category (shouldn't happen
      // post-backfill, but defensive in case the catalog shrinks).
      if (!byCat[cat]) continue;
      const bucket = byCat[cat][type] ?? { current: null, history: [] };
      if (doc.isCurrent) bucket.current = doc;
      else bucket.history.push(doc);
      byCat[cat][type] = bucket;
    }

    // Sort history newest-version-first inside every bucket so the popover
    // reads top-down: v3 (latest) → v2 → v1.
    for (const cat of DOCUMENT_CATEGORIES) {
      for (const type of Object.keys(byCat[cat])) {
        byCat[cat][type].history.sort(
          (a, b) => (b.version ?? 0) - (a.version ?? 0),
        );
      }
    }
    return byCat;
  }, [documents]);

  if (isLoading) {
    return (
      <div className="space-y-2">
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-24 w-full" />
        <Skeleton className="h-24 w-full" />
      </div>
    );
  }

  return (
    <Tabs
      value={activeTab}
      onValueChange={(v) => setActiveTab(v as DocumentCategory)}
      className="space-y-4"
    >
      <TabsList className="grid grid-cols-2 sm:grid-cols-4 w-full">
        {DOCUMENT_CATEGORIES.map((cat) => (
          <TabsTrigger
            key={cat}
            value={cat}
            data-testid={`tab-document-category-${cat}`}
          >
            {t(`assets.docs.category.${cat}`, cat)}
          </TabsTrigger>
        ))}
      </TabsList>

      {DOCUMENT_CATEGORIES.map((cat) => (
        <TabsContent key={cat} value={cat} className="space-y-3">
          <DocumentCategoryPanel
            trailerId={trailerId}
            category={cat}
            byType={grouped[cat]}
          />
        </TabsContent>
      ))}
    </Tabs>
  );
}

function DocumentCategoryPanel({
  trailerId,
  category,
  byType,
}: {
  trailerId: string;
  category: DocumentCategory;
  byType: GroupedByType;
}) {
  const { t } = useTranslation();
  const types = DOCUMENT_TYPE_CATALOG[category];

  return (
    <div className="space-y-3" data-testid={`panel-document-category-${category}`}>
      {types.map((typeDef) => {
        const bucket = byType[typeDef.type] ?? { current: null, history: [] };
        // The catalog has no human-readable label — labels come from i18n.
        // We pass the raw type id as the fallback so the UI never shows a
        // blank cell if a translation key is missing.
        return (
          <DocumentTypeRow
            key={typeDef.type}
            trailerId={trailerId}
            category={category}
            typeId={typeDef.type}
            typeLabel={t(`assets.docs.type.${typeDef.type}`, typeDef.type)}
            required={typeDef.required}
            current={bucket.current}
            history={bucket.history}
          />
        );
      })}
      {types.length === 0 && (
        <p className="text-sm text-muted-foreground text-center py-4">
          {t("assets.docs.noTypes", "No document types configured for this section.")}
        </p>
      )}
    </div>
  );
}

function DocumentTypeRow({
  trailerId,
  category,
  typeId,
  typeLabel,
  required,
  current,
  history,
}: {
  trailerId: string;
  category: DocumentCategory;
  typeId: string;
  typeLabel: string;
  required: boolean;
  current: EnrichedDocument | null;
  history: EnrichedDocument[];
}) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const { user } = useAuth();
  const isManager = user?.role === "manager" || user?.role === "admin";
  const { uploadFile, isUploading } = useUpload();
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [rejectOpen, setRejectOpen] = useState(false);
  const [rejectReason, setRejectReason] = useState("");

  const invalidate = () =>
    queryClient.invalidateQueries({
      queryKey: ["/api/trailers", trailerId, "documents"],
    });

  const uploadMutation = useMutation({
    mutationFn: async (file: File) => {
      const result = await uploadFile(file);
      if (!result) throw new Error("Upload aborted");
      return apiRequest("POST", `/api/trailers/${trailerId}/documents`, {
        category,
        documentType: typeId,
        fileName: file.name,
        fileUrl: result.objectPath,
        fileSize: file.size,
        mimeType: file.type || null,
      });
    },
    onSuccess: () => {
      invalidate();
      toast({
        title: t("assets.docs.uploadSuccess", "Document uploaded"),
        description: t(
          "assets.docs.uploadSuccessDesc",
          "The document was saved and is awaiting review.",
        ),
      });
    },
    onError: (err: any) => {
      toast({
        title: t("assets.docs.uploadError", "Upload failed"),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (docId: string) =>
      apiRequest("DELETE", `/api/trailers/${trailerId}/documents/${docId}`),
    onSuccess: () => {
      invalidate();
      toast({ title: t("assets.docs.deleted", "Document deleted") });
    },
    onError: (err: any) => {
      toast({
        title: t("assets.docs.deleteError", "Delete failed"),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  const statusMutation = useMutation({
    mutationFn: async (args: {
      docId: string;
      status: DocumentStatus;
      rejectionReason?: string;
    }) =>
      apiRequest(
        "PATCH",
        `/api/trailers/${trailerId}/documents/${args.docId}/status`,
        { status: args.status, rejectionReason: args.rejectionReason },
      ),
    onSuccess: (_data, vars) => {
      invalidate();
      setRejectOpen(false);
      setRejectReason("");
      toast({
        title:
          vars.status === "approved"
            ? t("assets.docs.approved", "Document approved")
            : t("assets.docs.rejected", "Document rejected"),
      });
    },
    onError: (err: any) => {
      toast({
        title: t("assets.docs.statusError", "Failed to update status"),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  const onFilePicked = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    uploadMutation.mutate(file);
  };

  const status = (current?.status ?? "pending") as DocumentStatus;
  const busy =
    isUploading ||
    uploadMutation.isPending ||
    deleteMutation.isPending ||
    statusMutation.isPending;

  return (
    <Card data-testid={`row-document-type-${typeId}`}>
      <CardContent className="p-4 flex flex-col gap-3">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h4
                className="font-medium truncate"
                data-testid={`text-document-type-${typeId}`}
              >
                {typeLabel}
              </h4>
              {required && (
                <Badge variant="outline" className="text-xs">
                  {t("assets.docs.required", "Required")}
                </Badge>
              )}
              {current ? (
                <Badge
                  variant={statusBadgeVariant(status)}
                  data-testid={`status-document-${typeId}`}
                >
                  {t(`assets.docs.status.${status}`, status)}
                </Badge>
              ) : (
                <Badge
                  variant={required ? "destructive" : "secondary"}
                  data-testid={`status-document-${typeId}`}
                >
                  {required
                    ? t("assets.docs.missing", "Missing")
                    : t("assets.docs.notUploaded", "Not uploaded")}
                </Badge>
              )}
              {current && (current.version ?? 1) > 1 && (
                <Badge variant="outline" className="text-xs">
                  v{current.version}
                </Badge>
              )}
            </div>

            {current ? (
              <div className="mt-2 flex items-center gap-2 min-w-0 text-sm">
                <FileText className="h-4 w-4 text-muted-foreground shrink-0" />
                <span
                  className="truncate"
                  data-testid={`text-document-name-${typeId}`}
                >
                  {current.fileName}
                </span>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground mt-2">
                {t(
                  "assets.docs.noFile",
                  "No file uploaded yet for this document type.",
                )}
              </p>
            )}

            {current && (
              <div className="mt-1 flex flex-wrap gap-x-3 gap-y-0.5 text-xs text-muted-foreground">
                {current.uploadedAt && (
                  <span>
                    {format(new Date(current.uploadedAt), "MM/dd/yyyy HH:mm")}
                  </span>
                )}
                {current.uploader && (
                  <span data-testid={`text-document-uploader-${typeId}`}>
                    {t("assets.docs.uploadedBy", "by")} {current.uploader.name}
                  </span>
                )}
                {current.reviewer && current.reviewedAt && (
                  <span data-testid={`text-document-reviewer-${typeId}`}>
                    {status === "approved"
                      ? t("assets.docs.approvedBy", "approved by")
                      : t("assets.docs.rejectedBy", "rejected by")}{" "}
                    {current.reviewer.name} ·{" "}
                    {format(new Date(current.reviewedAt), "MM/dd/yyyy")}
                  </span>
                )}
              </div>
            )}

            {current?.status === "rejected" && current.rejectionReason && (
              <p className="mt-1 text-xs text-destructive">
                {t("assets.docs.reason", "Reason")}: {current.rejectionReason}
              </p>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2 shrink-0">
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*,application/pdf"
              className="hidden"
              onChange={onFilePicked}
              data-testid={`input-upload-document-${typeId}`}
            />
            <Button
              size="sm"
              variant={current ? "outline" : "default"}
              onClick={() => fileInputRef.current?.click()}
              disabled={busy}
              data-testid={`button-${current ? "replace" : "upload"}-document-${typeId}`}
            >
              {current ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-1" />
                  {t("assets.docs.replace", "Replace")}
                </>
              ) : (
                <>
                  <Upload className="h-4 w-4 mr-1" />
                  {t("assets.docs.upload", "Upload")}
                </>
              )}
            </Button>

            {current && (
              <>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => window.open(current.fileUrl, "_blank")}
                  data-testid={`button-view-document-${typeId}`}
                  title={t("assets.docs.view", "View")}
                >
                  <Eye className="h-4 w-4" />
                </Button>
                {history.length > 0 && (
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        size="sm"
                        variant="outline"
                        data-testid={`button-history-document-${typeId}`}
                        title={t("assets.docs.history", "Version history")}
                      >
                        <HistoryIcon className="h-4 w-4" />
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-80" align="end">
                      <p className="text-xs font-semibold uppercase text-muted-foreground mb-2">
                        {t("assets.docs.history", "Version history")}
                      </p>
                      <ul className="space-y-2">
                        {history.map((v) => (
                          <li
                            key={v.id}
                            className="flex items-center justify-between gap-2 text-sm"
                            data-testid={`row-document-history-${v.id}`}
                          >
                            <div className="min-w-0 flex-1">
                              <p className="truncate">
                                <span className="font-mono text-xs mr-1.5">
                                  v{v.version}
                                </span>
                                {v.fileName}
                              </p>
                              <p className="text-xs text-muted-foreground">
                                {v.uploadedAt &&
                                  format(
                                    new Date(v.uploadedAt),
                                    "MM/dd/yyyy",
                                  )}
                                {v.uploader ? ` · ${v.uploader.name}` : ""}
                              </p>
                            </div>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() =>
                                window.open(v.fileUrl, "_blank")
                              }
                              data-testid={`button-view-document-version-${v.id}`}
                            >
                              <Eye className="h-4 w-4" />
                            </Button>
                          </li>
                        ))}
                      </ul>
                    </PopoverContent>
                  </Popover>
                )}
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    if (
                      confirm(
                        t(
                          "assets.docs.confirmDelete",
                          "Delete this document version?",
                        ),
                      )
                    ) {
                      deleteMutation.mutate(current.id);
                    }
                  }}
                  disabled={busy}
                  data-testid={`button-delete-document-${typeId}`}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </>
            )}
          </div>
        </div>

        {/* Approve / Reject controls — managers only, only meaningful while
            the document is pending. */}
        {current && isManager && status === "pending" && (
          <div className="flex items-center gap-2 pt-2 border-t">
            <Button
              size="sm"
              variant="default"
              onClick={() =>
                statusMutation.mutate({
                  docId: current.id,
                  status: "approved",
                })
              }
              disabled={busy}
              data-testid={`button-approve-document-${typeId}`}
            >
              <CheckCircle className="h-4 w-4 mr-1" />
              {t("assets.docs.approve", "Approve")}
            </Button>
            <Button
              size="sm"
              variant="destructive"
              onClick={() => setRejectOpen(true)}
              disabled={busy}
              data-testid={`button-reject-document-${typeId}`}
            >
              {t("assets.docs.reject", "Reject")}
            </Button>
          </div>
        )}
      </CardContent>

      <Dialog open={rejectOpen} onOpenChange={setRejectOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {t("assets.docs.rejectTitle", "Reject document")}
            </DialogTitle>
            <DialogDescription>
              {t(
                "assets.docs.rejectDesc",
                "Tell the uploader why this document is being rejected.",
              )}
            </DialogDescription>
          </DialogHeader>
          <Input
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
            placeholder={t(
              "assets.docs.reasonPlaceholder",
              "e.g., expired, illegible, wrong document",
            )}
            maxLength={500}
            data-testid={`input-reject-reason-${typeId}`}
          />
          <div className="flex justify-end gap-2">
            <Button
              variant="outline"
              onClick={() => setRejectOpen(false)}
              data-testid={`button-cancel-reject-${typeId}`}
            >
              {t("common.cancel", "Cancel")}
            </Button>
            <Button
              variant="destructive"
              disabled={!rejectReason.trim() || statusMutation.isPending}
              onClick={() =>
                current &&
                statusMutation.mutate({
                  docId: current.id,
                  status: "rejected",
                  rejectionReason: rejectReason.trim(),
                })
              }
              data-testid={`button-confirm-reject-${typeId}`}
            >
              {t("assets.docs.confirmReject", "Reject document")}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </Card>
  );
}

type TrailerAuditLogEntry = {
  id: string;
  action: string;
  entityType: string;
  entityId: string | null;
  details: any;
  ipAddress: string | null;
  timestamp: string;
  user: { id: string; username: string; email: string; role: string } | null;
};

function TrailerHistoryTab({ trailerId }: { trailerId: string }) {
  const { t } = useTranslation();

  const { data: logs, isLoading, isError } = useQuery<TrailerAuditLogEntry[]>({
    queryKey: ["/api/trailers", trailerId, "audit-logs"],
  });

  if (isLoading) {
    return (
      <div className="space-y-3" data-testid="history-loading">
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
      </div>
    );
  }

  if (isError) {
    return (
      <div
        className="p-4 rounded-md bg-destructive/10 text-destructive text-sm"
        data-testid="history-error"
      >
        {t('assets.history.loadError', 'Failed to load history.')}
      </div>
    );
  }

  if (!logs || logs.length === 0) {
    return (
      <div
        className="p-6 text-center text-sm text-muted-foreground border border-dashed rounded-md"
        data-testid="history-empty"
      >
        {t('assets.history.empty', 'No changes have been recorded for this asset yet.')}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div>
        <h3 className="font-semibold text-lg" data-testid="text-history-title">
          {t('assets.history.title', 'Edit History')}
        </h3>
        <p className="text-sm text-muted-foreground">
          {t('assets.history.description', 'Who changed this asset, when, and which fields were updated.')}
        </p>
      </div>

      <div className="space-y-3" data-testid="list-history-entries">
        {logs.map((entry) => (
          <HistoryEntry key={entry.id} entry={entry} />
        ))}
      </div>
    </div>
  );
}

function HistoryEntry({ entry }: { entry: TrailerAuditLogEntry }) {
  const { t } = useTranslation();
  const [showDetails, setShowDetails] = useState(false);

  // entry.user is null in two cases: (a) the originating user was deleted,
  // and (b) the audit log row was written without a userId (system jobs
  // such as the cron-driven invoice/payment generators). We can tell them
  // apart by looking at entry.userId — present-but-not-joined means the
  // user was deleted, missing means it was a system action.
  const userLabel = entry.user
    ? entry.user.username || entry.user.email
    : (entry as any).userId
      ? t('assets.history.unknownUser', 'Removed user')
      : t('assets.history.systemUser', 'System');

  const actionLabel = t(
    `assets.history.actions.${entry.action}`,
    entry.action.replace(/_/g, ' '),
  );

  const changedFields: string[] = Array.isArray(entry.details?.changedFields)
    ? entry.details.changedFields
    : [];

  let formattedTime = entry.timestamp;
  try {
    formattedTime = format(new Date(entry.timestamp), "dd/MM/yyyy HH:mm");
  } catch {
    /* fall back to raw string */
  }

  const hasDetailsPayload =
    entry.details && typeof entry.details === "object" && Object.keys(entry.details).length > 0;

  return (
    <div
      className="border rounded-md p-3 bg-muted/20 space-y-2"
      data-testid={`history-entry-${entry.id}`}
    >
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="flex items-start gap-2 min-w-0">
          <div className="mt-0.5 text-muted-foreground">
            <HistoryIcon className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <p
              className="font-medium text-sm"
              data-testid={`text-history-action-${entry.id}`}
            >
              {actionLabel}
            </p>
            <p className="text-xs text-muted-foreground flex items-center gap-1.5 mt-0.5">
              <UserIcon className="h-3 w-3" />
              <span data-testid={`text-history-user-${entry.id}`}>{userLabel}</span>
              {entry.user?.role && (
                <Badge variant="outline" className="text-[10px] px-1.5 py-0 h-4">
                  {entry.user.role}
                </Badge>
              )}
            </p>
          </div>
        </div>
        <div
          className="text-xs text-muted-foreground font-mono whitespace-nowrap"
          data-testid={`text-history-timestamp-${entry.id}`}
        >
          {formattedTime}
        </div>
      </div>

      <div className="text-xs">
        <span className="text-muted-foreground">
          {t('assets.history.changedFields', 'Changed fields')}:
        </span>{" "}
        {changedFields.length > 0 ? (
          <span className="flex flex-wrap gap-1 mt-1" data-testid={`list-history-fields-${entry.id}`}>
            {changedFields.map((field) => (
              <Badge key={field} variant="secondary" className="text-[10px]">
                {field}
              </Badge>
            ))}
          </span>
        ) : (
          <span className="text-muted-foreground italic">
            {t('assets.history.noFieldsChanged', 'No field details')}
          </span>
        )}
      </div>

      {hasDetailsPayload && (
        <Collapsible open={showDetails} onOpenChange={setShowDetails}>
          <CollapsibleTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="h-6 px-2 text-xs"
              data-testid={`button-toggle-history-details-${entry.id}`}
            >
              <ChevronDown
                className={`h-3 w-3 mr-1 transition-transform ${showDetails ? "rotate-180" : ""}`}
              />
              {showDetails
                ? t('assets.history.hideDetails', 'Hide details')
                : t('assets.history.showDetails', 'Show details')}
            </Button>
          </CollapsibleTrigger>
          <CollapsibleContent>
            <pre
              className="mt-2 p-2 rounded bg-background/60 border text-[11px] font-mono overflow-x-auto"
              data-testid={`text-history-details-${entry.id}`}
            >
              {JSON.stringify(entry.details, null, 2)}
            </pre>
          </CollapsibleContent>
        </Collapsible>
      )}
    </div>
  );
}
