import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Download, Eye, Plus } from "lucide-react";
import { format } from "date-fns";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { insertTrailerSchema, type InsertTrailer } from "@shared/schema";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { formatCurrency } from "@/lib/currency";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/hooks/useAuth";

export default function Assets() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [detailsDialogOpen, setDetailsDialogOpen] = useState(false);
  const [selectedTrailer, setSelectedTrailer] = useState<any>(null);
  const [allocationType, setAllocationType] = useState<"open" | "specific">("open");
  const [investorSearchQuery, setInvestorSearchQuery] = useState("");
  const { toast } = useToast();
  
  const { data: trailers, isLoading } = useQuery({
    queryKey: ["/api/trailers"],
  });

  const { data: investors } = useQuery({
    queryKey: ["/api/investors"],
  });

  const form = useForm<InsertTrailer & { allocationType?: string; investorId?: string }>({
    resolver: zodResolver(insertTrailerSchema),
    defaultValues: {
      trailerId: "", // Will be auto-generated by backend
      trailerType: "Seco",
      model: "",
      purchaseValue: "",
      purchaseDate: new Date().toISOString().split('T')[0],
      currentValue: "",
      status: "stock",
      depreciationRate: "0.05",
      location: "",
      latitude: "",
      longitude: "",
      totalShares: 1,
      allocationType: "open",
      investorId: "",
    },
  });

  const createTrailerMutation = useMutation({
    mutationFn: async (data: InsertTrailer) => {
      return await apiRequest("POST", "/api/trailers", data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers"] });
      toast({
        title: t('assets.successTitle'),
        description: t('assets.successDescription'),
      });
      setDialogOpen(false);
      form.reset();
    },
    onError: (error: any) => {
      // Check if we have field-specific errors from the backend
      if (error.errors && typeof error.errors === 'object') {
        // Set errors on specific fields with translated messages
        Object.entries(error.errors).forEach(([field, message]) => {
          // Check if the message is a translation key
          const translatedMessage = t(`assets.${message}`, { defaultValue: message as string });
          form.setError(field as any, {
            type: 'manual',
            message: translatedMessage,
          });
        });
        
        // Show toast with translated main error message
        const translatedError = t(`assets.${error.message}`, { defaultValue: t('assets.errorDescription') });
        toast({
          title: t('assets.errorTitle'),
          description: translatedError,
          variant: "destructive",
        });
      } else {
        // Generic error handling
        const translatedError = error.message ? t(`assets.${error.message}`, { defaultValue: error.message }) : t('assets.errorDescription');
        toast({
          title: t('assets.errorTitle'),
          description: translatedError,
          variant: "destructive",
        });
      }
    },
  });

  const onSubmit = (data: InsertTrailer & { allocationType?: string; investorId?: string }) => {
    // Remove latitude/longitude if they're empty strings
    const cleanedData = {
      ...data,
      latitude: data.latitude === "" ? undefined : data.latitude,
      longitude: data.longitude === "" ? undefined : data.longitude,
      allocationType: data.allocationType || "open",
      investorId: data.allocationType === "specific" ? data.investorId : undefined,
    };
    createTrailerMutation.mutate(cleanedData as any);
  };

  const getStatusBadge = (status: string) => {
    const variants: Record<string, { variant: any; label: string }> = {
      active: { variant: "default", label: t('assets.statusActive') },
      stock: { variant: "secondary", label: t('assets.statusStock') },
      maintenance: { variant: "outline", label: t('assets.statusMaintenance') },
      expired: { variant: "destructive", label: t('assets.statusExpired') },
    };
    return variants[status] || variants.stock;
  };

  const getTrafficLight = (purchaseDate: string) => {
    const purchase = new Date(purchaseDate);
    const now = new Date();
    const monthsDiff = (now.getTime() - purchase.getTime()) / (1000 * 60 * 60 * 24 * 30);
    
    if (monthsDiff < 12) return "bg-green-500";
    if (monthsDiff < 24) return "bg-yellow-500";
    return "bg-red-500";
  };

  const handleExport = () => {
    if (!trailers || trailers.length === 0) {
      toast({
        title: t('assets.noDataToExport'),
        description: t('assets.noAssetsRegistered'),
        variant: "destructive",
      });
      return;
    }

    const statusTranslations: Record<string, string> = {
      stock: t('assets.statusStock'),
      active: t('assets.statusActive'),
      maintenance: t('assets.statusMaintenance'),
      expired: t('assets.statusExpired'),
    };

    const headers = [
      t('assets.trailerId'),
      t('assets.status'),
      t('assets.sharesSold'),
      t('assets.totalShares'),
      t('assets.sharesAvailable'),
      t('assets.purchaseValue'),
      t('assets.currentValue'),
      t('assets.purchaseDate'),
      t('assets.depreciationRate'),
      t('assets.location'),
      t('assets.latitude'),
      t('assets.longitude')
    ];

    // Função para formatar valores monetários no padrão brasileiro
    const formatCurrency = (value: string | number) => {
      const num = parseFloat(String(value));
      const formatted = num.toLocaleString('pt-BR', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      });
      return `$ ${formatted}`;
    };

    const csvData = trailers.map((trailer: any) => [
      trailer.trailerId,
      statusTranslations[trailer.status] || trailer.status,
      trailer.soldShares || 0,
      trailer.totalShares || 1,
      (trailer.totalShares || 1) - (trailer.soldShares || 0),
      formatCurrency(trailer.purchaseValue),
      formatCurrency(trailer.currentValue),
      format(new Date(trailer.purchaseDate), "dd/MM/yyyy"),
      trailer.depreciationRate || "0",
      trailer.location || "",
      trailer.latitude || "",
      trailer.longitude || "",
    ]);

    const csvRows = [
      headers.join(";"),
      ...csvData.map((row: any[]) => 
        row.map((cell: any) => {
          const cellStr = String(cell);
          if (cellStr.includes(";") || cellStr.includes(",") || cellStr.includes('"') || cellStr.includes("\n")) {
            return `"${cellStr.replace(/"/g, '""')}"`;
          }
          return cellStr;
        }).join(";")
      )
    ];

    const BOM = "\uFEFF";
    const csvContent = BOM + csvRows.join("\r\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    
    link.setAttribute("href", url);
    link.setAttribute("download", `ativos_opus_rental_${format(new Date(), "yyyy-MM-dd")}.csv`);
    link.style.visibility = "hidden";
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast({
      title: t('assets.exportSuccess'),
      description: t('assets.exportDescription'),
    });
  };

  if (isLoading) {
    return (
      <div className="p-6">
        <Skeleton className="h-96" />
      </div>
    );
  }

  return (
    <div className="p-3 sm:p-4 md:p-6 lg:p-8 space-y-4 sm:space-y-6 lg:space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-foreground">{t('assets.title')}</h1>
          <p className="text-sm text-muted-foreground mt-1">{t('assets.subtitle')}</p>
        </div>
        <div className="flex gap-3">
          <Button 
            className="bg-accent hover:bg-accent/90 shadow-lg" 
            data-testid="button-new-asset"
            onClick={() => setDialogOpen(true)}
          >
            <Plus className="mr-2 h-4 w-4" />
            {t('assets.newAsset')}
          </Button>
          <Button 
            variant="outline" 
            className="border-2" 
            data-testid="button-export"
            onClick={handleExport}
          >
            <Download className="mr-2 h-4 w-4" />
            {t('assets.export')}
          </Button>
        </div>
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{t('assets.newAssetDialog')}</DialogTitle>
            <DialogDescription>
              {t('assets.newAssetDescription')}
            </DialogDescription>
          </DialogHeader>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="trailerType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.trailerType')}</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-trailer-type">
                            <SelectValue placeholder={t('assets.selectTrailerType')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Seco">{t('assets.trailerTypeSeco')}</SelectItem>
                          <SelectItem value="Climatizado">{t('assets.trailerTypeClimatizado')}</SelectItem>
                          <SelectItem value="Lonado">{t('assets.trailerTypeLonado')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                      <p className="text-xs text-muted-foreground mt-1">
                        {t('assets.autoIdHint', 'ID será gerado automaticamente (ex: TRS001, TRC002, TRL003)')}
                      </p>
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="allocationType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.allocationType')}</FormLabel>
                      <Select 
                        onValueChange={(value) => {
                          field.onChange(value);
                          setAllocationType(value as "open" | "specific");
                        }} 
                        defaultValue={field.value}
                      >
                        <FormControl>
                          <SelectTrigger data-testid="select-allocation-type">
                            <SelectValue placeholder={t('assets.selectAllocationType')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="open">{t('assets.allocationTypeOpen')}</SelectItem>
                          <SelectItem value="specific">{t('assets.allocationTypeSpecific')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                      <p className="text-xs text-muted-foreground mt-1">
                        {allocationType === "open" ? t('assets.allocationOpenHint') : t('assets.allocationSpecificHint')}
                      </p>
                    </FormItem>
                  )}
                />
              </div>

              {allocationType === "specific" && (
                <div className="grid grid-cols-1 gap-4">
                  <div className="space-y-2">
                    <FormLabel>{t('assets.selectInvestor')}</FormLabel>
                    <Input
                      placeholder={t('assets.searchInvestor')}
                      value={investorSearchQuery}
                      onChange={(e) => setInvestorSearchQuery(e.target.value)}
                      className="mb-2"
                      data-testid="input-search-investor"
                    />
                  </div>
                  <FormField
                    control={form.control}
                    name="investorId"
                    render={({ field }) => (
                      <FormItem>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-investor">
                              <SelectValue placeholder={t('assets.selectInvestorPlaceholder')} />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {investors
                              ?.filter((investor: any) => {
                                const searchLower = investorSearchQuery.toLowerCase();
                                const fullName = `${investor.firstName} ${investor.lastName}`.toLowerCase();
                                const email = investor.email.toLowerCase();
                                return fullName.includes(searchLower) || email.includes(searchLower);
                              })
                              .map((investor: any) => (
                                <SelectItem key={investor.id} value={investor.id}>
                                  {investor.firstName} {investor.lastName} ({investor.email})
                                </SelectItem>
                              ))}
                            {investors?.filter((investor: any) => {
                              const searchLower = investorSearchQuery.toLowerCase();
                              const fullName = `${investor.firstName} ${investor.lastName}`.toLowerCase();
                              const email = investor.email.toLowerCase();
                              return fullName.includes(searchLower) || email.includes(searchLower);
                            }).length === 0 && (
                              <div className="px-2 py-6 text-center text-sm text-muted-foreground">
                                {t('assets.noInvestorsFound')}
                              </div>
                            )}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              )}

              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="model"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.model')}</FormLabel>
                      <FormControl>
                        <Input placeholder="Dry Van 53ft" {...field} data-testid="input-model" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="status"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.status')}</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-status">
                            <SelectValue placeholder={t('assets.selectStatus')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="stock">{t('assets.statusStock')}</SelectItem>
                          <SelectItem value="active">{t('assets.statusActive')}</SelectItem>
                          <SelectItem value="maintenance">{t('assets.statusMaintenance')}</SelectItem>
                          <SelectItem value="expired">{t('assets.statusExpired')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="purchaseValue"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.purchaseValue')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="50000.00" {...field} data-testid="input-purchase-value" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="currentValue"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.currentValue')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="50000.00" {...field} data-testid="input-current-value" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="purchaseDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.purchaseDate')}</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} data-testid="input-purchase-date" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="depreciationRate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.depreciationRate')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="0.05" {...field} data-testid="input-depreciation-rate" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="totalShares"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.totalShares')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          min="1" 
                          placeholder="1" 
                          {...field} 
                          value={field.value || 1}
                          onChange={(e) => field.onChange(parseInt(e.target.value) || 1)}
                          data-testid="input-total-shares" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="location"
                  render={({ field }) => (
                    <FormItem className="col-span-2">
                      <FormLabel>{t('assets.location')}</FormLabel>
                      <FormControl>
                        <Input placeholder="Houston, TX" {...field} value={field.value || ""} data-testid="input-location" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="latitude"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.latitude')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          step="0.0000001" 
                          placeholder="29.7604" 
                          {...field} 
                          value={field.value || ""} 
                          data-testid="input-latitude" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="longitude"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.longitude')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          step="0.0000001" 
                          placeholder="-95.3698" 
                          {...field} 
                          value={field.value || ""} 
                          data-testid="input-longitude" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="flex justify-end gap-3 pt-4">
                <Button 
                  type="button" 
                  variant="outline" 
                  onClick={() => setDialogOpen(false)}
                  data-testid="button-cancel"
                >
                  {t('assets.cancel')}
                </Button>
                <Button 
                  type="submit" 
                  className="bg-accent hover:bg-accent/90"
                  disabled={createTrailerMutation.isPending}
                  data-testid="button-submit-asset"
                >
                  {createTrailerMutation.isPending ? t('assets.creating') : t('assets.createAsset')}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>

      {/* Modal de Detalhes do Ativo */}
      <Dialog open={detailsDialogOpen} onOpenChange={setDetailsDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-2xl font-bold text-primary">
              {t('assets.detailsDialog')}
            </DialogTitle>
            <DialogDescription>
              {t('assets.detailsDescription')}
            </DialogDescription>
          </DialogHeader>
          
          {selectedTrailer && (
            <div className="space-y-6 mt-4">
              {/* Informações Básicas */}
              <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                <h3 className="font-semibold text-lg mb-3">{t('assets.basicInfo')}</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.trailerId')}</label>
                    <p className="font-bold text-primary text-lg">{selectedTrailer.trailerId}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.model')}</label>
                    <p className="font-semibold">{selectedTrailer.model || "—"}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.status')}</label>
                    <div className="mt-1">
                      <Badge variant={getStatusBadge(selectedTrailer.status).variant} className="rounded-full">
                        {getStatusBadge(selectedTrailer.status).label}
                      </Badge>
                    </div>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.purchaseDate')}</label>
                    <p className="font-semibold">
                      {format(new Date(selectedTrailer.purchaseDate), "dd/MM/yyyy")}
                    </p>
                  </div>
                </div>
              </div>

              {/* Informações Financeiras */}
              <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                <h3 className="font-semibold text-lg mb-3">{t('assets.financialInfo')}</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.purchaseValueLabel')}</label>
                    <p className="font-bold text-lg">${parseFloat(selectedTrailer.purchaseValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.currentValueLabel')}</label>
                    <p className="font-bold text-lg">${parseFloat(selectedTrailer.currentValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.depreciationRate')}</label>
                    <p className="font-semibold">{(parseFloat(selectedTrailer.depreciationRate) * 100).toFixed(1)}%</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.ageIndicator')}</label>
                    <div className="flex items-center gap-2 mt-1">
                      <div className={`w-5 h-5 ${getTrafficLight(selectedTrailer.purchaseDate)} rounded-full shadow-lg`}></div>
                      <span className="text-sm text-muted-foreground">
                        {getTrafficLight(selectedTrailer.purchaseDate) === "bg-green-500" && t('assets.lessThan1Year')}
                        {getTrafficLight(selectedTrailer.purchaseDate) === "bg-yellow-500" && t('assets.between1And2Years')}
                        {getTrafficLight(selectedTrailer.purchaseDate) === "bg-red-500" && t('assets.moreThan2Years')}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Informações de Cotas */}
              <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                <h3 className="font-semibold text-lg mb-3">{t('assets.sharesInfo')}</h3>
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.totalShares')}</label>
                    <p className="font-bold text-lg">{selectedTrailer.totalShares || 1}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.sharesSold')}</label>
                    <p className="font-bold text-lg">{selectedTrailer.soldShares || 0}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.sharesAvailable')}</label>
                    <p className="font-bold text-lg text-accent">
                      {(selectedTrailer.totalShares || 1) - (selectedTrailer.soldShares || 0)}
                    </p>
                  </div>
                </div>
              </div>

              {/* Localização */}
              <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                <h3 className="font-semibold text-lg mb-3">{t('assets.location')}</h3>
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.cityState')}</label>
                    <p className="font-semibold">{selectedTrailer.location || "—"}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.latitude')}</label>
                    <p className="font-mono text-sm">{selectedTrailer.latitude || "—"}</p>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground">{t('assets.longitude')}</label>
                    <p className="font-mono text-sm">{selectedTrailer.longitude || "—"}</p>
                  </div>
                </div>
              </div>

              <div className="flex justify-end pt-4">
                <Button 
                  onClick={() => setDetailsDialogOpen(false)}
                  className="bg-accent hover:bg-accent/90"
                  data-testid="button-close-details"
                >
                  {t('assets.close')}
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      <Card className="shadow-lg">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-muted/50">
                <tr>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">ID</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableType')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableModel')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.status')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableShares')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableTrafficLight')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tablePurchaseValue')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableValue')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableAcquisition')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableLocation')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableActions')}</th>
                </tr>
              </thead>
              <tbody>
                {trailers?.map((trailer: any) => {
                  const statusInfo = getStatusBadge(trailer.status);
                  return (
                    <tr
                      key={trailer.id}
                      className="border-b border-border hover:bg-accent/5 transition-colors"
                      data-testid={`trailer-${trailer.id}`}
                    >
                      <td className="py-4 px-6">
                        <span className="font-bold text-primary">{trailer.trailerId}</span>
                      </td>
                      <td className="py-4 px-6">
                        <Badge variant="outline" className="font-medium">
                          {trailer.trailerType === "Seco" ? t('assets.trailerTypeSeco') : 
                           trailer.trailerType === "Climatizado" ? t('assets.trailerTypeClimatizado') : 
                           trailer.trailerType === "Lonado" ? t('assets.trailerTypeLonado') : 
                           trailer.trailerType || "—"}
                        </Badge>
                      </td>
                      <td className="py-4 px-6">
                        <span className="text-foreground">{trailer.model || "—"}</span>
                      </td>
                      <td className="py-4 px-6">
                        <Badge variant={statusInfo.variant} className="rounded-full">
                          {statusInfo.label}
                        </Badge>
                      </td>
                      <td className="py-4 px-6">
                        <span className="font-semibold text-foreground" data-testid={`text-shares-${trailer.id}`}>
                          {trailer.soldShares || 0}/{trailer.totalShares || 1}
                        </span>
                      </td>
                      <td className="py-4 px-6">
                        <div className="flex items-center gap-2">
                          <div className={`w-4 h-4 ${getTrafficLight(trailer.purchaseDate)} rounded-full shadow-lg`}></div>
                        </div>
                      </td>
                      <td className="py-4 px-6">
                        <span className="font-semibold text-muted-foreground">
                          {formatCurrency(parseFloat(trailer.purchaseValue), user?.country)}
                        </span>
                      </td>
                      <td className="py-4 px-6">
                        <span className="font-bold text-foreground">
                          {formatCurrency(parseFloat(trailer.currentValue), user?.country)}
                        </span>
                      </td>
                      <td className="py-4 px-6 text-muted-foreground">
                        {format(new Date(trailer.purchaseDate), "dd/MM/yyyy")}
                      </td>
                      <td className="py-4 px-6 text-muted-foreground">{trailer.location || "—"}</td>
                      <td className="py-4 px-6">
                        <Button 
                          variant="ghost" 
                          size="icon" 
                          className="hover:bg-accent/20 hover:text-accent" 
                          onClick={() => {
                            setSelectedTrailer(trailer);
                            setDetailsDialogOpen(true);
                          }}
                          data-testid={`button-view-${trailer.id}`}
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                      </td>
                    </tr>
                  );
                })}
                {(!trailers || trailers.length === 0) && (
                  <tr>
                    <td colSpan={11} className="text-center py-12 text-muted-foreground">
                      {t('assets.noAssets')}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
