import { useEffect, useMemo, useRef, useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  arrayMove,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Download, Eye, Plus, Check, ChevronsUpDown, ChevronDown, Upload, FileText, Trash2, Search, Pencil, RefreshCw, GripVertical, History as HistoryIcon, User as UserIcon } from "lucide-react";
import { format } from "date-fns";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { insertTrailerSchema, type InsertTrailer, type Trailer, type TrailerDocument } from "@shared/schema";
import { z } from "zod";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { formatCurrency } from "@/lib/currency";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/hooks/useAuth";
import { useUpload } from "@/hooks/use-upload";

const assetFormSchema = insertTrailerSchema.extend({
  allocationType: z.enum(["open", "specific"]).default("open"),
  investorId: z.string().optional(),
}).superRefine((data, ctx) => {
  if (data.allocationType === "specific" && !data.investorId) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: "Investor is required when allocation type is 'specific'",
      path: ["investorId"],
    });
  }
});

type AssetFormData = z.infer<typeof assetFormSchema>;

export default function Assets() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingTrailer, setEditingTrailer] = useState<any | null>(null);
  const [detailsDialogOpen, setDetailsDialogOpen] = useState(false);
  const [selectedTrailer, setSelectedTrailer] = useState<any>(null);
  const [allocationType, setAllocationType] = useState<"open" | "specific">("open");
  const [investorComboOpen, setInvestorComboOpen] = useState(false);
  const isEditing = !!editingTrailer;
  // Trailer list filters (year/make/vehicleUse + free text against vin/titleNumber/trailerId)
  const [filterSearch, setFilterSearch] = useState("");
  const [filterYear, setFilterYear] = useState<string>("all");
  const [filterMake, setFilterMake] = useState<string>("all");
  const [filterVehicleUse, setFilterVehicleUse] = useState<string>("all");
  const { toast } = useToast();
  
  const { data: trailers, isLoading } = useQuery<any[]>({
    queryKey: ["/api/trailers"],
  });

  const { data: investors } = useQuery({
    queryKey: ["/api/investors"],
  });

  const form = useForm<AssetFormData>({
    resolver: zodResolver(assetFormSchema),
    defaultValues: {
      trailerId: "", // Will be auto-generated by backend
      trailerType: "Seco",
      model: "",
      purchaseValue: "",
      purchaseDate: new Date().toISOString().split('T')[0],
      currentValue: "",
      status: "stock",
      depreciationRate: "0.05",
      location: "",
      latitude: "",
      longitude: "",
      totalShares: 1,
      allocationType: "open",
      investorId: "",
      vin: "",
      year: undefined,
      make: "",
      body: "",
      weightLbs: undefined,
      titleNumber: "",
      vehicleUse: undefined,
      titleDate: "",
      imageData: "",
    },
  });

  const closeDialog = () => {
    setDialogOpen(false);
    setEditingTrailer(null);
    setAllocationType("open");
    form.reset();
  };

  const createTrailerMutation = useMutation({
    mutationFn: async (data: InsertTrailer) => {
      return await apiRequest("POST", "/api/trailers", data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers"] });
      toast({
        title: t('assets.successTitle'),
        description: t('assets.successDescription'),
      });
      closeDialog();
    },
    onError: (error: any) => {
      // Check if we have field-specific errors from the backend
      if (error.errors && typeof error.errors === 'object') {
        // Set errors on specific fields with translated messages
        Object.entries(error.errors).forEach(([field, message]) => {
          // Check if the message is a translation key
          const translatedMessage = t(`assets.${message}`, { defaultValue: message as string });
          form.setError(field as any, {
            type: 'manual',
            message: translatedMessage,
          });
        });
        
        // Show toast with translated main error message
        const translatedError = t(`assets.${error.message}`, { defaultValue: t('assets.errorDescription') });
        toast({
          title: t('assets.errorTitle'),
          description: translatedError,
          variant: "destructive",
        });
      } else {
        // Generic error handling
        const translatedError = error.message ? t(`assets.${error.message}`, { defaultValue: error.message }) : t('assets.errorDescription');
        toast({
          title: t('assets.errorTitle'),
          description: translatedError,
          variant: "destructive",
        });
      }
    },
  });

  const updateTrailerMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<InsertTrailer> }) => {
      const res = await apiRequest("PATCH", `/api/trailers/${id}`, data);
      return (await res.json()) as Trailer;
    },
    onSuccess: (updated: Trailer) => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers"] });
      // The PATCH endpoint writes a new audit log entry, so refresh the
      // History tab's cached query for this trailer too — otherwise the
      // tab keeps showing stale data because audit-log queries reuse the
      // global Infinity staleTime.
      queryClient.invalidateQueries({
        queryKey: ["/api/trailers", updated.id, "audit-logs"],
      });
      toast({
        title: t('assets.editSuccessTitle', 'Ativo atualizado'),
        description: t('assets.editSuccessDescription', 'As alterações foram salvas com sucesso.'),
      });
      // Keep the details dialog in sync if it is open for this trailer.
      if (selectedTrailer && selectedTrailer.id === updated.id) {
        setSelectedTrailer({ ...selectedTrailer, ...updated });
      }
      closeDialog();
    },
    onError: (error: any) => {
      if (error.errors && typeof error.errors === 'object') {
        Object.entries(error.errors).forEach(([field, message]) => {
          const translatedMessage = t(`assets.${message}`, { defaultValue: message as string });
          form.setError(field as any, { type: 'manual', message: translatedMessage });
        });
        const translatedError = t(`assets.${error.message}`, { defaultValue: t('assets.errorDescription') });
        toast({ title: t('assets.errorTitle'), description: translatedError, variant: "destructive" });
      } else {
        const translatedError = error.message ? t(`assets.${error.message}`, { defaultValue: error.message }) : t('assets.errorDescription');
        toast({ title: t('assets.errorTitle'), description: translatedError, variant: "destructive" });
      }
    },
  });

  const onSubmit = (data: AssetFormData) => {
    console.log("✅ Form submitted with data:", data);
    console.log("✅ Form errors:", form.formState.errors);

    // Normalize: convert "" → undefined for every optional vehicle/location
    // field so the backend stores NULL rather than persisting empty strings
    // (which would defeat indexes and downstream filters).
    const optionalStringFields = [
      "latitude",
      "longitude",
      "vin",
      "make",
      "body",
      "titleNumber",
      "vehicleUse",
      "titleDate",
      "imageData",
    ] as const;

    const cleanedData: Record<string, any> = { ...data };
    for (const key of optionalStringFields) {
      if (cleanedData[key] === "" || cleanedData[key] === null) {
        cleanedData[key] = undefined;
      }
    }
    // Numeric optionals: drop empty / NaN values so Zod treats them as missing.
    for (const key of ["year", "weightLbs"] as const) {
      if (cleanedData[key] === "" || cleanedData[key] === null || Number.isNaN(cleanedData[key])) {
        cleanedData[key] = undefined;
      }
    }

    if (isEditing && editingTrailer) {
      // PATCH: drop allocation-only and server-managed fields that don't
      // belong to a partial trailer update.
      const { allocationType: _a, investorId: _i, trailerId: _tid, ...patchData } = cleanedData;
      console.log("✅ Update payload:", patchData);
      updateTrailerMutation.mutate({ id: editingTrailer.id, data: patchData as Partial<InsertTrailer> });
      return;
    }

    cleanedData.allocationType = data.allocationType || "open";
    cleanedData.investorId = data.allocationType === "specific" ? data.investorId : undefined;

    console.log("✅ Cleaned data:", cleanedData);
    createTrailerMutation.mutate(cleanedData as any);
  };

  const openEditDialog = (trailer: any) => {
    setEditingTrailer(trailer);
    setAllocationType("open"); // hidden in edit mode anyway
    form.reset({
      trailerId: trailer.trailerId ?? "",
      trailerType: trailer.trailerType ?? "Seco",
      model: trailer.model ?? "",
      purchaseValue: trailer.purchaseValue ?? "",
      purchaseDate: trailer.purchaseDate
        ? new Date(trailer.purchaseDate).toISOString().split('T')[0]
        : new Date().toISOString().split('T')[0],
      currentValue: trailer.currentValue ?? "",
      status: trailer.status ?? "stock",
      depreciationRate: trailer.depreciationRate ?? "0.05",
      location: trailer.location ?? "",
      latitude: trailer.latitude ?? "",
      longitude: trailer.longitude ?? "",
      totalShares: trailer.totalShares ?? 1,
      allocationType: "open",
      investorId: "",
      vin: trailer.vin ?? "",
      year: trailer.year ?? undefined,
      make: trailer.make ?? "",
      body: trailer.body ?? "",
      weightLbs: trailer.weightLbs ?? undefined,
      titleNumber: trailer.titleNumber ?? "",
      vehicleUse:
        trailer.vehicleUse === "PRIVATE" || trailer.vehicleUse === "COMMERCIAL"
          ? trailer.vehicleUse
          : undefined,
      titleDate: trailer.titleDate
        ? new Date(trailer.titleDate).toISOString().split('T')[0]
        : "",
      imageData: trailer.imageData ?? "",
    } as AssetFormData);
    setDialogOpen(true);
  };

  const onFormError = (errors: any) => {
    console.error("❌ Form validation failed:", errors);
    
    // Show toast with validation errors
    const errorMessages = Object.entries(errors)
      .map(([field, error]: [string, any]) => `${field}: ${error.message}`)
      .join('\n');
    
    toast({
      title: t('assets.validationError', 'Erros de validação'),
      description: errorMessages,
      variant: "destructive",
    });
  };

  // Distinct year/make/vehicleUse values for filter dropdowns
  const filterOptions = useMemo(() => {
    const list = trailers ?? [];
    const years = Array.from(new Set(list.map((t: any) => t.year).filter((v: any) => v != null))).sort((a: any, b: any) => b - a);
    const makes = Array.from(new Set(list.map((t: any) => t.make).filter(Boolean))).sort() as string[];
    const uses = Array.from(new Set(list.map((t: any) => t.vehicleUse).filter(Boolean))).sort() as string[];
    return { years, makes, uses };
  }, [trailers]);

  const filteredTrailers = useMemo(() => {
    const list = trailers ?? [];
    const term = filterSearch.trim().toLowerCase();
    return list.filter((trailer: any) => {
      if (filterYear !== "all" && String(trailer.year ?? "") !== filterYear) return false;
      if (filterMake !== "all" && (trailer.make ?? "") !== filterMake) return false;
      if (filterVehicleUse !== "all" && (trailer.vehicleUse ?? "") !== filterVehicleUse) return false;
      if (term) {
        const hay = `${trailer.trailerId ?? ""} ${trailer.vin ?? ""} ${trailer.titleNumber ?? ""}`.toLowerCase();
        if (!hay.includes(term)) return false;
      }
      return true;
    });
  }, [trailers, filterYear, filterMake, filterVehicleUse, filterSearch]);

  const getStatusBadge = (status: string) => {
    const variants: Record<string, { variant: any; label: string }> = {
      active: { variant: "default", label: t('assets.statusActive') },
      stock: { variant: "secondary", label: t('assets.statusStock') },
      maintenance: { variant: "outline", label: t('assets.statusMaintenance') },
      expired: { variant: "destructive", label: t('assets.statusExpired') },
    };
    return variants[status] || variants.stock;
  };

  const getTrafficLight = (purchaseDate: string) => {
    const purchase = new Date(purchaseDate);
    const now = new Date();
    const monthsDiff = (now.getTime() - purchase.getTime()) / (1000 * 60 * 60 * 24 * 30);
    
    if (monthsDiff < 12) return "bg-green-500";
    if (monthsDiff < 24) return "bg-yellow-500";
    return "bg-red-500";
  };

  const handleExport = () => {
    if (!trailers || trailers.length === 0) {
      toast({
        title: t('assets.noDataToExport'),
        description: t('assets.noAssetsRegistered'),
        variant: "destructive",
      });
      return;
    }

    const statusTranslations: Record<string, string> = {
      stock: t('assets.statusStock'),
      active: t('assets.statusActive'),
      maintenance: t('assets.statusMaintenance'),
      expired: t('assets.statusExpired'),
    };

    const headers = [
      t('assets.trailerId'),
      t('assets.status'),
      t('assets.sharesSold'),
      t('assets.totalShares'),
      t('assets.sharesAvailable'),
      t('assets.purchaseValue'),
      t('assets.currentValue'),
      t('assets.purchaseDate'),
      t('assets.depreciationRate'),
      t('assets.location'),
      t('assets.latitude'),
      t('assets.longitude')
    ];

    // Função para formatar valores monetários no padrão brasileiro
    const formatCurrency = (value: string | number) => {
      const num = parseFloat(String(value));
      const formatted = num.toLocaleString('pt-BR', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      });
      return `$ ${formatted}`;
    };

    const csvData = trailers.map((trailer: any) => [
      trailer.trailerId,
      statusTranslations[trailer.status] || trailer.status,
      trailer.soldShares || 0,
      trailer.totalShares || 1,
      (trailer.totalShares || 1) - (trailer.soldShares || 0),
      formatCurrency(trailer.purchaseValue),
      formatCurrency(trailer.currentValue),
      format(new Date(trailer.purchaseDate), "dd/MM/yyyy"),
      trailer.depreciationRate || "0",
      trailer.location || "",
      trailer.latitude || "",
      trailer.longitude || "",
    ]);

    const csvRows = [
      headers.join(";"),
      ...csvData.map((row: any[]) => 
        row.map((cell: any) => {
          const cellStr = String(cell);
          if (cellStr.includes(";") || cellStr.includes(",") || cellStr.includes('"') || cellStr.includes("\n")) {
            return `"${cellStr.replace(/"/g, '""')}"`;
          }
          return cellStr;
        }).join(";")
      )
    ];

    const BOM = "\uFEFF";
    const csvContent = BOM + csvRows.join("\r\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    
    link.setAttribute("href", url);
    link.setAttribute("download", `ativos_opus_rental_${format(new Date(), "yyyy-MM-dd")}.csv`);
    link.style.visibility = "hidden";
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast({
      title: t('assets.exportSuccess'),
      description: t('assets.exportDescription'),
    });
  };

  if (isLoading) {
    return (
      <div className="p-6">
        <Skeleton className="h-96" />
      </div>
    );
  }

  return (
    <div className="p-3 sm:p-4 md:p-6 lg:p-8 space-y-4 sm:space-y-6 lg:space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-foreground">{t('assets.title')}</h1>
          <p className="text-sm text-muted-foreground mt-1">{t('assets.subtitle')}</p>
        </div>
        <div className="flex gap-3">
          <Button
            className="bg-accent hover:bg-accent/90 shadow-lg"
            data-testid="button-new-asset"
            onClick={() => {
              setEditingTrailer(null);
              setAllocationType("open");
              form.reset();
              setDialogOpen(true);
            }}
          >
            <Plus className="mr-2 h-4 w-4" />
            {t('assets.newAsset')}
          </Button>
          <Button 
            variant="outline" 
            className="border-2" 
            data-testid="button-export"
            onClick={handleExport}
          >
            <Download className="mr-2 h-4 w-4" />
            {t('assets.export')}
          </Button>
        </div>
      </div>

      <Dialog
        open={dialogOpen}
        onOpenChange={(open) => {
          if (!open) closeDialog();
          else setDialogOpen(true);
        }}
      >
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle data-testid="text-asset-dialog-title">
              {isEditing
                ? t('assets.editAssetDialog', 'Editar Ativo')
                : t('assets.newAssetDialog')}
            </DialogTitle>
            <DialogDescription>
              {isEditing
                ? t('assets.editAssetDescription', 'Atualize as informações do veículo. Apenas os campos modificados serão salvos.')
                : t('assets.newAssetDescription')}
            </DialogDescription>
          </DialogHeader>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit, onFormError)} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="trailerType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.trailerType')}</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-trailer-type">
                            <SelectValue placeholder={t('assets.selectTrailerType')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Seco">{t('assets.trailerTypeSeco')}</SelectItem>
                          <SelectItem value="Climatizado">{t('assets.trailerTypeClimatizado')}</SelectItem>
                          <SelectItem value="Lonado">{t('assets.trailerTypeLonado')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                      {!isEditing && (
                        <p className="text-xs text-muted-foreground mt-1">
                          {t('assets.autoIdHint', 'ID será gerado automaticamente (ex: TRS001, TRC002, TRL003)')}
                        </p>
                      )}
                      {isEditing && editingTrailer?.trailerId && (
                        <p className="text-xs text-muted-foreground mt-1" data-testid="text-edit-trailer-id">
                          {t('assets.trailerId')}: <span className="font-mono">{editingTrailer.trailerId}</span>
                        </p>
                      )}
                    </FormItem>
                  )}
                />

                {!isEditing && (
                  <FormField
                    control={form.control}
                    name="allocationType"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.allocationType')}</FormLabel>
                        <Select
                          onValueChange={(value) => {
                            field.onChange(value);
                            setAllocationType(value as "open" | "specific");
                          }}
                          defaultValue={field.value}
                        >
                          <FormControl>
                            <SelectTrigger data-testid="select-allocation-type">
                              <SelectValue placeholder={t('assets.selectAllocationType')} />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="open">{t('assets.allocationTypeOpen')}</SelectItem>
                            <SelectItem value="specific">{t('assets.allocationTypeSpecific')}</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                        <p className="text-xs text-muted-foreground mt-1">
                          {allocationType === "open" ? t('assets.allocationOpenHint') : t('assets.allocationSpecificHint')}
                        </p>
                      </FormItem>
                    )}
                  />
                )}
              </div>

              {!isEditing && allocationType === "specific" && (
                <div className="grid grid-cols-1 gap-4">
                  <FormField
                    control={form.control}
                    name="investorId"
                    render={({ field }) => (
                      <FormItem className="flex flex-col">
                        <FormLabel>{t('assets.selectInvestor')}</FormLabel>
                        <Popover open={investorComboOpen} onOpenChange={setInvestorComboOpen}>
                          <PopoverTrigger asChild>
                            <FormControl>
                              <Button
                                variant="outline"
                                role="combobox"
                                aria-expanded={investorComboOpen}
                                className="w-full justify-between"
                                data-testid="button-select-investor"
                              >
                                {field.value
                                  ? investors?.find((investor: any) => investor.id === field.value)
                                    ? `${investors.find((inv: any) => inv.id === field.value).firstName} ${investors.find((inv: any) => inv.id === field.value).lastName} (${investors.find((inv: any) => inv.id === field.value).email})`
                                    : t('assets.selectInvestorPlaceholder')
                                  : t('assets.selectInvestorPlaceholder')}
                                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                              </Button>
                            </FormControl>
                          </PopoverTrigger>
                          <PopoverContent className="w-[400px] p-0">
                            <Command>
                              <CommandInput placeholder={t('assets.searchInvestor')} />
                              <CommandList>
                                <CommandEmpty>{t('assets.noInvestorsFound')}</CommandEmpty>
                                <CommandGroup>
                                  {investors?.map((investor: any) => {
                                    const searchValue = `${investor.firstName} ${investor.lastName} ${investor.email}`.toLowerCase();
                                    return (
                                      <CommandItem
                                        key={investor.id}
                                        value={searchValue}
                                        onSelect={() => {
                                          form.setValue("investorId", investor.id);
                                          setInvestorComboOpen(false);
                                        }}
                                      >
                                        <Check
                                          className={`mr-2 h-4 w-4 ${
                                            field.value === investor.id ? "opacity-100" : "opacity-0"
                                          }`}
                                        />
                                        {investor.firstName} {investor.lastName} ({investor.email})
                                      </CommandItem>
                                    );
                                  })}
                                </CommandGroup>
                              </CommandList>
                            </Command>
                          </PopoverContent>
                        </Popover>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              )}

              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="model"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.model')}</FormLabel>
                      <FormControl>
                        <Input placeholder="Dry Van 53ft" {...field} data-testid="input-model" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="status"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.status')}</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-status">
                            <SelectValue placeholder={t('assets.selectStatus')} />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="stock">{t('assets.statusStock')}</SelectItem>
                          <SelectItem value="active">{t('assets.statusActive')}</SelectItem>
                          <SelectItem value="maintenance">{t('assets.statusMaintenance')}</SelectItem>
                          <SelectItem value="expired">{t('assets.statusExpired')}</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="purchaseValue"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.purchaseValue')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="50000.00" {...field} data-testid="input-purchase-value" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="currentValue"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.currentValue')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="50000.00" {...field} data-testid="input-current-value" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="purchaseDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.purchaseDate')}</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} data-testid="input-purchase-date" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="depreciationRate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.depreciationRate')}</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="0.05" {...field} data-testid="input-depreciation-rate" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="totalShares"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.totalShares')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          min="1" 
                          placeholder="1" 
                          {...field} 
                          value={field.value || 1}
                          onChange={(e) => field.onChange(parseInt(e.target.value) || 1)}
                          data-testid="input-total-shares" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="location"
                  render={({ field }) => (
                    <FormItem className="col-span-2">
                      <FormLabel>{t('assets.location')}</FormLabel>
                      <FormControl>
                        <Input placeholder="Houston, TX" {...field} value={field.value || ""} data-testid="input-location" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="latitude"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.latitude')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          step="0.0000001" 
                          placeholder="29.7604" 
                          {...field} 
                          value={field.value || ""} 
                          data-testid="input-latitude" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="longitude"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('assets.longitude')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          step="0.0000001" 
                          placeholder="-95.3698" 
                          {...field} 
                          value={field.value || ""} 
                          data-testid="input-longitude" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              {/* Vehicle identification fields — all optional, collapsible */}
              <Collapsible className="border-t pt-2 mt-2">
                <CollapsibleTrigger
                  className="flex w-full items-center justify-between py-2 group"
                  data-testid="button-toggle-vehicle-id"
                >
                  <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">
                    {t('assets.vehicleIdSection', 'Identificação do Veículo')}
                  </h4>
                  <ChevronDown className="h-4 w-4 text-muted-foreground transition-transform group-data-[state=open]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="pt-3">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="vin"
                    render={({ field }) => (
                      <FormItem className="col-span-2">
                        <FormLabel>{t('assets.vin', 'VIN')}</FormLabel>
                        <FormControl>
                          <Input placeholder="1HGBH41JXMN109186" {...field} value={field.value ?? ""} data-testid="input-vin" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="year"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.year', 'Ano')}</FormLabel>
                        <FormControl>
                          <Input
                            type="number"
                            min="1900"
                            max="2100"
                            placeholder="2024"
                            {...field}
                            value={field.value ?? ""}
                            onChange={(e) => field.onChange(e.target.value === "" ? undefined : Number(e.target.value))}
                            data-testid="input-year"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="make"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.make', 'Marca')}</FormLabel>
                        <FormControl>
                          <Input placeholder="Great Dane" {...field} value={field.value ?? ""} data-testid="input-make" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="body"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.body', 'Carroceria')}</FormLabel>
                        <FormControl>
                          <Input placeholder="Dry Van" {...field} value={field.value ?? ""} data-testid="input-body" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="weightLbs"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.weightLbs', 'Peso (lbs)')}</FormLabel>
                        <FormControl>
                          <Input
                            type="number"
                            min="0"
                            placeholder="14000"
                            {...field}
                            value={field.value ?? ""}
                            onChange={(e) => field.onChange(e.target.value === "" ? undefined : Number(e.target.value))}
                            data-testid="input-weight-lbs"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="titleNumber"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.titleNumber', 'Nº do Título')}</FormLabel>
                        <FormControl>
                          <Input placeholder="TX1234567890" {...field} value={field.value ?? ""} data-testid="input-title-number" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="vehicleUse"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.vehicleUse', 'Uso do Veículo')}</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value ?? ""}>
                          <FormControl>
                            <SelectTrigger data-testid="select-vehicle-use">
                              <SelectValue placeholder={t('assets.selectVehicleUse', 'Selecione o uso')} />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="PRIVATE">{t('assets.vehicleUsePrivate', 'Privado')}</SelectItem>
                            <SelectItem value="COMMERCIAL">{t('assets.vehicleUseCommercial', 'Comercial')}</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="titleDate"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('assets.titleDate', 'Data do Título')}</FormLabel>
                        <FormControl>
                          <Input type="date" {...field} value={field.value ?? ""} data-testid="input-title-date" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
                </CollapsibleContent>
              </Collapsible>

              <div className="flex justify-end gap-3 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={closeDialog}
                  data-testid="button-cancel"
                >
                  {t('assets.cancel')}
                </Button>
                <Button
                  type="submit"
                  className="bg-accent hover:bg-accent/90"
                  disabled={createTrailerMutation.isPending || updateTrailerMutation.isPending}
                  data-testid="button-submit-asset"
                >
                  {isEditing
                    ? updateTrailerMutation.isPending
                      ? t('assets.saving', 'Salvando...')
                      : t('assets.saveChanges', 'Salvar alterações')
                    : createTrailerMutation.isPending
                      ? t('assets.creating')
                      : t('assets.createAsset')}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>

      {/* Modal de Detalhes do Ativo */}
      <Dialog open={detailsDialogOpen} onOpenChange={setDetailsDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-2xl font-bold text-primary">
              {t('assets.detailsDialog')}
            </DialogTitle>
            <DialogDescription>
              {t('assets.detailsDescription')}
            </DialogDescription>
          </DialogHeader>
          
          {selectedTrailer && (
            <Tabs defaultValue="overview" className="mt-4">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="overview" data-testid="tab-overview">
                  {t('assets.tabOverview', 'Visão Geral')}
                </TabsTrigger>
                <TabsTrigger value="documents" data-testid="tab-documents">
                  {t('assets.tabDocuments', 'Documentos')}
                </TabsTrigger>
                <TabsTrigger value="history" data-testid="tab-history">
                  {t('assets.tabHistory', 'Histórico')}
                </TabsTrigger>
              </TabsList>

              <TabsContent value="overview" className="space-y-6 mt-4">
                {/* Informações Básicas */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.basicInfo')}</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.trailerId')}</label>
                      <p className="font-bold text-primary text-lg">{selectedTrailer.trailerId}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.model')}</label>
                      <p className="font-semibold">{selectedTrailer.model || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.status')}</label>
                      <div className="mt-1">
                        <Badge variant={getStatusBadge(selectedTrailer.status).variant} className="rounded-full">
                          {getStatusBadge(selectedTrailer.status).label}
                        </Badge>
                      </div>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.purchaseDate')}</label>
                      <p className="font-semibold">
                        {format(new Date(selectedTrailer.purchaseDate), "dd/MM/yyyy")}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Vehicle Identification */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.vehicleIdSection', 'Identificação do Veículo')}</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="col-span-2">
                      <label className="text-sm text-muted-foreground">{t('assets.vin', 'VIN')}</label>
                      <p className="font-mono text-sm" data-testid="text-detail-vin">{selectedTrailer.vin || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.year', 'Ano')}</label>
                      <p className="font-semibold">{selectedTrailer.year ?? "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.make', 'Marca')}</label>
                      <p className="font-semibold">{selectedTrailer.make || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.body', 'Carroceria')}</label>
                      <p className="font-semibold">{selectedTrailer.body || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.weightLbs', 'Peso (lbs)')}</label>
                      <p className="font-semibold">{selectedTrailer.weightLbs ?? "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.titleNumber', 'Nº do Título')}</label>
                      <p className="font-mono text-sm">{selectedTrailer.titleNumber || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.vehicleUse', 'Uso do Veículo')}</label>
                      <p className="font-semibold">
                        {selectedTrailer.vehicleUse === "PRIVATE"
                          ? t('assets.vehicleUsePrivate', 'Privado')
                          : selectedTrailer.vehicleUse === "COMMERCIAL"
                            ? t('assets.vehicleUseCommercial', 'Comercial')
                            : "—"}
                      </p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.titleDate', 'Data do Título')}</label>
                      <p className="font-semibold">
                        {selectedTrailer.titleDate
                          ? format(new Date(selectedTrailer.titleDate), "dd/MM/yyyy")
                          : "—"}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Informações Financeiras */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.financialInfo')}</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.purchaseValueLabel')}</label>
                      <p className="font-bold text-lg">${parseFloat(selectedTrailer.purchaseValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.currentValueLabel')}</label>
                      <p className="font-bold text-lg">${parseFloat(selectedTrailer.currentValue).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.depreciationRate')}</label>
                      <p className="font-semibold">{(parseFloat(selectedTrailer.depreciationRate) * 100).toFixed(1)}%</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.ageIndicator')}</label>
                      <div className="flex items-center gap-2 mt-1">
                        <div className={`w-5 h-5 ${getTrafficLight(selectedTrailer.purchaseDate)} rounded-full shadow-lg`}></div>
                        <span className="text-sm text-muted-foreground">
                          {getTrafficLight(selectedTrailer.purchaseDate) === "bg-green-500" && t('assets.lessThan1Year')}
                          {getTrafficLight(selectedTrailer.purchaseDate) === "bg-yellow-500" && t('assets.between1And2Years')}
                          {getTrafficLight(selectedTrailer.purchaseDate) === "bg-red-500" && t('assets.moreThan2Years')}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Informações de Cotas */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.sharesInfo')}</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.totalShares')}</label>
                      <p className="font-bold text-lg">{selectedTrailer.totalShares || 1}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.sharesSold')}</label>
                      <p className="font-bold text-lg">{selectedTrailer.soldShares || 0}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.sharesAvailable')}</label>
                      <p className="font-bold text-lg text-accent">
                        {(selectedTrailer.totalShares || 1) - (selectedTrailer.soldShares || 0)}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Localização */}
                <div className="bg-muted/30 p-4 rounded-lg space-y-3">
                  <h3 className="font-semibold text-lg mb-3">{t('assets.location')}</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.cityState')}</label>
                      <p className="font-semibold">{selectedTrailer.location || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.latitude')}</label>
                      <p className="font-mono text-sm">{selectedTrailer.latitude || "—"}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground">{t('assets.longitude')}</label>
                      <p className="font-mono text-sm">{selectedTrailer.longitude || "—"}</p>
                    </div>
                  </div>
                </div>

                <div className="flex justify-end gap-3 pt-4">
                  <Button
                    variant="outline"
                    onClick={() => {
                      setDetailsDialogOpen(false);
                      openEditDialog(selectedTrailer);
                    }}
                    data-testid="button-edit-from-details"
                  >
                    <Pencil className="h-4 w-4 mr-2" />
                    {t('assets.editAsset', 'Editar Ativo')}
                  </Button>
                  <Button
                    onClick={() => setDetailsDialogOpen(false)}
                    className="bg-accent hover:bg-accent/90"
                    data-testid="button-close-details"
                  >
                    {t('assets.close')}
                  </Button>
                </div>
              </TabsContent>

              <TabsContent value="documents" className="mt-4">
                <TrailerDocumentsTab trailerId={selectedTrailer.id} />
              </TabsContent>

              <TabsContent value="history" className="mt-4">
                <TrailerHistoryTab trailerId={selectedTrailer.id} />
              </TabsContent>
            </Tabs>
          )}
        </DialogContent>
      </Dialog>

      {/* Filters */}
      <Card className="shadow-sm">
        <CardContent className="p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              value={filterSearch}
              onChange={(e) => setFilterSearch(e.target.value)}
              placeholder={t('assets.filterSearchPlaceholder', 'ID, VIN ou nº do título')}
              className="pl-9"
              data-testid="input-filter-search"
            />
          </div>
          <Select value={filterYear} onValueChange={setFilterYear}>
            <SelectTrigger data-testid="select-filter-year">
              <SelectValue placeholder={t('assets.year', 'Ano')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('assets.filterAll', 'Todos os anos')}</SelectItem>
              {filterOptions.years.map((y: any) => (
                <SelectItem key={y} value={String(y)}>{String(y)}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={filterMake} onValueChange={setFilterMake}>
            <SelectTrigger data-testid="select-filter-make">
              <SelectValue placeholder={t('assets.make', 'Marca')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('assets.filterAllMakes', 'Todas as marcas')}</SelectItem>
              {filterOptions.makes.map((m: string) => (
                <SelectItem key={m} value={m}>{m}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={filterVehicleUse} onValueChange={setFilterVehicleUse}>
            <SelectTrigger data-testid="select-filter-vehicle-use">
              <SelectValue placeholder={t('assets.vehicleUse', 'Uso')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('assets.filterAllUses', 'Todos os usos')}</SelectItem>
              <SelectItem value="PRIVATE">{t('assets.vehicleUsePrivate', 'Privado')}</SelectItem>
              <SelectItem value="COMMERCIAL">{t('assets.vehicleUseCommercial', 'Comercial')}</SelectItem>
            </SelectContent>
          </Select>
        </CardContent>
      </Card>

      <Card className="shadow-lg">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-muted/50">
                <tr>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">ID</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableType')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableModel')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.status')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableShares')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableTrafficLight')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tablePurchaseValue')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableValue')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableAcquisition')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableLocation')}</th>
                  <th className="text-left py-4 px-6 font-semibold text-muted-foreground">{t('assets.tableActions')}</th>
                </tr>
              </thead>
              <tbody>
                {filteredTrailers.map((trailer: any) => {
                  const statusInfo = getStatusBadge(trailer.status);
                  return (
                    <tr
                      key={trailer.id}
                      className="border-b border-border hover:bg-accent/5 transition-colors"
                      data-testid={`trailer-${trailer.id}`}
                    >
                      <td className="py-4 px-6">
                        <span className="font-bold text-primary">{trailer.trailerId}</span>
                      </td>
                      <td className="py-4 px-6">
                        <Badge variant="outline" className="font-medium">
                          {trailer.trailerType === "Seco" ? t('assets.trailerTypeSeco') : 
                           trailer.trailerType === "Climatizado" ? t('assets.trailerTypeClimatizado') : 
                           trailer.trailerType === "Lonado" ? t('assets.trailerTypeLonado') : 
                           trailer.trailerType || "—"}
                        </Badge>
                      </td>
                      <td className="py-4 px-6">
                        <span className="text-foreground">{trailer.model || "—"}</span>
                      </td>
                      <td className="py-4 px-6">
                        <Badge variant={statusInfo.variant} className="rounded-full">
                          {statusInfo.label}
                        </Badge>
                      </td>
                      <td className="py-4 px-6">
                        <span className="font-semibold text-foreground" data-testid={`text-shares-${trailer.id}`}>
                          {trailer.soldShares || 0}/{trailer.totalShares || 1}
                        </span>
                      </td>
                      <td className="py-4 px-6">
                        <div className="flex items-center gap-2">
                          <div className={`w-4 h-4 ${getTrafficLight(trailer.purchaseDate)} rounded-full shadow-lg`}></div>
                        </div>
                      </td>
                      <td className="py-4 px-6">
                        <span className="font-semibold text-muted-foreground">
                          {formatCurrency(parseFloat(trailer.purchaseValue), user?.country)}
                        </span>
                      </td>
                      <td className="py-4 px-6">
                        <span className="font-bold text-foreground">
                          {formatCurrency(parseFloat(trailer.currentValue), user?.country)}
                        </span>
                      </td>
                      <td className="py-4 px-6 text-muted-foreground">
                        {format(new Date(trailer.purchaseDate), "dd/MM/yyyy")}
                      </td>
                      <td className="py-4 px-6 text-muted-foreground">{trailer.location || "—"}</td>
                      <td className="py-4 px-6">
                        <div className="flex items-center gap-1">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="hover:bg-accent/20 hover:text-accent"
                            onClick={() => {
                              setSelectedTrailer(trailer);
                              setDetailsDialogOpen(true);
                            }}
                            data-testid={`button-view-${trailer.id}`}
                          >
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="hover:bg-accent/20 hover:text-accent"
                            onClick={() => openEditDialog(trailer)}
                            data-testid={`button-edit-${trailer.id}`}
                            title={t('assets.editAsset', 'Editar Ativo')}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
                {filteredTrailers.length === 0 && (
                  <tr>
                    <td colSpan={11} className="text-center py-12 text-muted-foreground">
                      {(!trailers || trailers.length === 0)
                        ? t('assets.noAssets')
                        : t('assets.noFilterResults', 'Nenhum ativo corresponde aos filtros aplicados')}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

const DOCUMENT_CATEGORIES = [
  "title",
  "registration",
  "insurance",
  "inspection",
  "purchase_invoice",
  "other",
] as const;

function TrailerDocumentsTab({ trailerId }: { trailerId: string }) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const [category, setCategory] = useState<string>("other");
  const { uploadFile, isUploading } = useUpload();
  // Hidden <input type="file"> used by the per-document "Replace" button.
  // We reuse a single input and stash the target document id on the element
  // so we don't have to render N inputs.
  const replaceInputRef = useRef<HTMLInputElement | null>(null);
  const [replacingDocId, setReplacingDocId] = useState<string | null>(null);

  type EnrichedDocument = TrailerDocument & {
    uploader?: { id: string; name: string; email: string | null } | null;
  };

  const { data: documents, isLoading } = useQuery<EnrichedDocument[]>({
    queryKey: ["/api/trailers", trailerId, "documents"],
  });

  // Local copy of the document list used to drive the rendered order. We
  // keep our own copy (rather than rendering directly from the query data)
  // so an in-flight reorder feels instant: the user sees the new order the
  // moment they release the drag, and we only fall back to server data once
  // the mutation completes (or fails).
  const [orderedDocs, setOrderedDocs] = useState<EnrichedDocument[]>([]);

  // Sort documents into a stable, category-grouped order. Within a category
  // the server already returns rows in `sortOrder` ASC, so we just preserve
  // the incoming order rather than re-sorting by upload date.
  const sortedDocuments = useMemo(() => {
    if (!documents) return [];
    const idx: Record<string, number> = Object.fromEntries(
      DOCUMENT_CATEGORIES.map((c, i) => [c, i]),
    );
    return [...documents].sort((a, b) => {
      const catCmp = (idx[a.documentCategory] ?? 99) - (idx[b.documentCategory] ?? 99);
      if (catCmp !== 0) return catCmp;
      return 0;
    });
  }, [documents]);

  // Sync local ordering whenever the server data changes (e.g. after an
  // upload, delete, or reorder confirmation).
  useEffect(() => {
    setOrderedDocs(sortedDocuments);
  }, [sortedDocuments]);

  // Normalize a possibly-legacy documentCategory value into a known bucket.
  // We have to use the same mapping in both the visual grouping AND the
  // reorder rebuild loop, otherwise a row shown under "other" would never
  // be matched when reordering that group.
  const normalizeCategory = (cat: string) =>
    (DOCUMENT_CATEGORIES as readonly string[]).includes(cat) ? cat : "other";

  // Group the ordered list by category so each category renders inside its
  // own SortableContext (drag is restricted to within a category).
  const docsByCategory = useMemo(() => {
    const groups: Record<string, EnrichedDocument[]> = {};
    for (const cat of DOCUMENT_CATEGORIES) groups[cat] = [];
    for (const doc of orderedDocs) {
      groups[normalizeCategory(doc.documentCategory)].push(doc);
    }
    return groups;
  }, [orderedDocs]);

  const createDocMutation = useMutation({
    mutationFn: async (payload: {
      fileUrl: string;
      fileName: string;
      documentCategory: string;
    }) => {
      return apiRequest("POST", `/api/trailers/${trailerId}/documents`, payload);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers", trailerId, "documents"] });
      toast({
        title: t('assets.docUploadSuccess', 'Documento enviado'),
        description: t('assets.docUploadSuccessDesc', 'O documento foi salvo com sucesso.'),
      });
    },
    onError: (err: any) => {
      toast({
        title: t('assets.docUploadError', 'Falha no upload'),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  const deleteDocMutation = useMutation({
    mutationFn: async (docId: string) => {
      return apiRequest("DELETE", `/api/trailers/${trailerId}/documents/${docId}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers", trailerId, "documents"] });
      toast({ title: t('assets.docDeleted', 'Documento excluído') });
    },
    onError: (err: any) => {
      toast({
        title: t('assets.docDeleteError', 'Falha ao excluir'),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  const updateDocMutation = useMutation({
    mutationFn: async ({ docId, documentCategory }: { docId: string; documentCategory: string }) => {
      return apiRequest("PATCH", `/api/trailers/${trailerId}/documents/${docId}`, {
        documentCategory,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers", trailerId, "documents"] });
      toast({ title: t('assets.docUpdated', 'Documento atualizado') });
    },
    onError: (err: any) => {
      toast({
        title: t('assets.docUpdateError', 'Falha ao atualizar'),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  const reorderDocsMutation = useMutation({
    mutationFn: async (orderedIds: string[]) => {
      return apiRequest("PATCH", `/api/trailers/${trailerId}/documents/reorder`, {
        orderedIds,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/trailers", trailerId, "documents"] });
    },
    onError: (err: any) => {
      // Roll back the optimistic order by re-syncing from the server.
      queryClient.invalidateQueries({ queryKey: ["/api/trailers", trailerId, "documents"] });
      toast({
        title: t('assets.docReorderError', 'Falha ao reordenar'),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    },
  });

  // Stable sensors so React doesn't recreate them on every render.
  const dndSensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 4 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }),
  );

  const handleDragEnd = (cat: string) => (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || active.id === over.id) return;

    const group = docsByCategory[cat];
    const oldIndex = group.findIndex((d) => d.id === active.id);
    const newIndex = group.findIndex((d) => d.id === over.id);
    if (oldIndex === -1 || newIndex === -1) return;

    const reorderedGroup = arrayMove(group, oldIndex, newIndex);

    // Rebuild the full ordered list, swapping in the reordered group for
    // the affected category — other categories stay where they are. Use
    // the normalized category here so legacy/unknown values that visually
    // sit in "other" are matched correctly.
    const newOrdered: EnrichedDocument[] = [];
    let groupCursor = 0;
    for (const doc of orderedDocs) {
      if (normalizeCategory(doc.documentCategory) === cat) {
        newOrdered.push(reorderedGroup[groupCursor++]);
      } else {
        newOrdered.push(doc);
      }
    }
    setOrderedDocs(newOrdered);
    reorderDocsMutation.mutate(newOrdered.map((d) => d.id));
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    const result = await uploadFile(file);
    if (!result) return;
    await createDocMutation.mutateAsync({
      fileUrl: result.objectPath,
      fileName: file.name,
      documentCategory: category,
    });
  };

  const startReplace = (docId: string) => {
    setReplacingDocId(docId);
    replaceInputRef.current?.click();
  };

  const handleReplaceFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    const docId = replacingDocId;
    if (!file || !docId) {
      setReplacingDocId(null);
      return;
    }
    const target = documents?.find((d) => d.id === docId);
    if (!target) {
      setReplacingDocId(null);
      return;
    }

    // Use apiRequest directly (instead of the per-document mutations) so
    // the replace flow surfaces a single consolidated toast and triggers
    // exactly one cache invalidation at the end. `replacingDocId` is kept
    // set throughout so the replace buttons stay disabled while the
    // upload + create + delete chain is in flight.
    try {
      const result = await uploadFile(file);
      if (!result) return;
      // Create the replacement first; only delete the previous record after
      // the new one is persisted, so a failure mid-flight never leaves the
      // category empty.
      await apiRequest("POST", `/api/trailers/${trailerId}/documents`, {
        fileUrl: result.objectPath,
        fileName: file.name,
        documentCategory: target.documentCategory,
      });
      await apiRequest("DELETE", `/api/trailers/${trailerId}/documents/${docId}`);
      queryClient.invalidateQueries({ queryKey: ["/api/trailers", trailerId, "documents"] });
      toast({
        title: t('assets.docReplaceSuccess', 'Documento substituído'),
        description: t('assets.docReplaceSuccessDesc', 'O arquivo foi atualizado mantendo a mesma categoria.'),
      });
    } catch (err: any) {
      console.error("Replace document failed:", err);
      toast({
        title: t('assets.docReplaceError', 'Falha ao substituir'),
        description: err?.message ?? String(err),
        variant: "destructive",
      });
    } finally {
      setReplacingDocId(null);
    }
  };

  const categoryLabel = (cat: string) =>
    t(`assets.docCategory.${cat}`, cat);

  return (
    <div className="space-y-4">
      <div className="bg-muted/30 p-4 rounded-lg flex flex-col sm:flex-row gap-3 sm:items-end">
        <div className="flex-1">
          <label className="text-sm font-medium mb-1 block">
            {t('assets.docCategoryLabel', 'Categoria')}
          </label>
          <Select value={category} onValueChange={setCategory}>
            <SelectTrigger data-testid="select-document-category">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {DOCUMENT_CATEGORIES.map((cat) => (
                <SelectItem key={cat} value={cat}>
                  {categoryLabel(cat)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="flex-1">
          <label className="text-sm font-medium mb-1 block">
            {t('assets.uploadDocument', 'Enviar documento')}
          </label>
          <div className="relative">
            <Input
              type="file"
              onChange={handleFileChange}
              disabled={isUploading || createDocMutation.isPending}
              data-testid="input-upload-document"
              accept="image/*,application/pdf"
            />
          </div>
        </div>
      </div>

      {/* Hidden replace input — shared across all rows; the active doc id is
          tracked in `replacingDocId`. */}
      <input
        ref={replaceInputRef}
        type="file"
        className="hidden"
        accept="image/*,application/pdf"
        onChange={handleReplaceFileChange}
        data-testid="input-replace-document"
      />

      {isLoading ? (
        <div className="space-y-2">
          <Skeleton className="h-16 w-full" />
          <Skeleton className="h-16 w-full" />
        </div>
      ) : !documents || documents.length === 0 ? (
        <div className="text-center py-8 text-muted-foreground">
          {t('assets.noDocuments', 'Nenhum documento anexado ainda.')}
        </div>
      ) : (
        <div className="space-y-6">
          {DOCUMENT_CATEGORIES.map((cat) => {
            const group = docsByCategory[cat];
            if (!group || group.length === 0) return null;
            return (
              <div key={cat} className="space-y-2" data-testid={`group-document-category-${cat}`}>
                <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
                  {categoryLabel(cat)}
                </h4>
                <DndContext
                  sensors={dndSensors}
                  collisionDetection={closestCenter}
                  onDragEnd={handleDragEnd(cat)}
                >
                  <SortableContext
                    items={group.map((d) => d.id)}
                    strategy={verticalListSortingStrategy}
                  >
                    <div className="space-y-2">
                      {group.map((doc) => (
                        <SortableDocumentRow
                          key={doc.id}
                          doc={doc}
                          onView={() => window.open(doc.fileUrl, "_blank")}
                          onReplace={() => startReplace(doc.id)}
                          onDelete={() => {
                            if (confirm(t('assets.confirmDeleteDoc', 'Excluir este documento?'))) {
                              deleteDocMutation.mutate(doc.id);
                            }
                          }}
                          onCategoryChange={(value) => {
                            if (value === doc.documentCategory) return;
                            updateDocMutation.mutate({ docId: doc.id, documentCategory: value });
                          }}
                          replaceDisabled={
                            isUploading ||
                            createDocMutation.isPending ||
                            deleteDocMutation.isPending ||
                            replacingDocId !== null
                          }
                          deleteDisabled={deleteDocMutation.isPending}
                          updateDisabled={updateDocMutation.isPending}
                          dragDisabled={reorderDocsMutation.isPending}
                          categories={DOCUMENT_CATEGORIES as readonly string[]}
                          categoryLabel={categoryLabel}
                          t={t}
                        />
                      ))}
                    </div>
                  </SortableContext>
                </DndContext>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

type SortableDocumentRowProps = {
  doc: TrailerDocument & {
    uploader?: { id: string; name: string; email: string | null } | null;
  };
  onView: () => void;
  onReplace: () => void;
  onDelete: () => void;
  onCategoryChange: (value: string) => void;
  replaceDisabled: boolean;
  deleteDisabled: boolean;
  updateDisabled: boolean;
  dragDisabled: boolean;
  categories: readonly string[];
  categoryLabel: (cat: string) => string;
  t: ReturnType<typeof useTranslation>["t"];
};

function SortableDocumentRow({
  doc,
  onView,
  onReplace,
  onDelete,
  onCategoryChange,
  replaceDisabled,
  deleteDisabled,
  updateDisabled,
  dragDisabled,
  categories,
  categoryLabel,
  t,
}: SortableDocumentRowProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: doc.id, disabled: dragDisabled });

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.6 : 1,
    zIndex: isDragging ? 10 : "auto",
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      className="flex flex-col sm:flex-row sm:items-center gap-3 p-3 border rounded-lg bg-background hover-elevate"
      data-testid={`row-document-${doc.id}`}
    >
      <div className="flex items-center gap-3 min-w-0 flex-1">
        <button
          type="button"
          disabled={dragDisabled}
          className={`touch-none p-1 -m-1 text-muted-foreground ${dragDisabled ? "cursor-not-allowed opacity-50" : "cursor-grab active:cursor-grabbing hover:text-foreground"}`}
          aria-label={t('assets.dragDocument', 'Arrastar para reordenar')}
          data-testid={`drag-handle-document-${doc.id}`}
          {...attributes}
          {...listeners}
        >
          <GripVertical className="h-4 w-4" />
        </button>
        <FileText className="h-5 w-5 text-muted-foreground shrink-0" />
        <div className="min-w-0 flex-1">
          <p className="font-medium truncate" data-testid={`text-document-name-${doc.id}`}>
            {doc.fileName}
          </p>
          <div className="flex flex-wrap items-center gap-x-2 gap-y-0.5 text-xs text-muted-foreground mt-0.5">
            {doc.uploadedAt && (
              <span data-testid={`text-document-date-${doc.id}`}>
                {format(new Date(doc.uploadedAt), "dd/MM/yyyy HH:mm")}
              </span>
            )}
            {doc.uploader && (
              <>
                <span>•</span>
                <span data-testid={`text-document-uploader-${doc.id}`}>
                  {t('assets.docUploadedBy', 'por')} {doc.uploader.name}
                </span>
              </>
            )}
          </div>
        </div>
      </div>
      <div className="flex items-center gap-2 shrink-0">
        <Select
          value={doc.documentCategory}
          onValueChange={onCategoryChange}
          disabled={updateDisabled}
        >
          <SelectTrigger
            className="h-8 min-w-[140px] text-xs"
            data-testid={`select-document-category-${doc.id}`}
          >
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {categories.map((cat) => (
              <SelectItem key={cat} value={cat}>
                {categoryLabel(cat)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Button
          variant="outline"
          size="sm"
          onClick={onView}
          data-testid={`button-view-document-${doc.id}`}
          title={t('assets.viewDocument', 'Visualizar')}
        >
          <Eye className="h-4 w-4" />
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={onReplace}
          disabled={replaceDisabled}
          data-testid={`button-replace-document-${doc.id}`}
          title={t('assets.replaceDocument', 'Substituir arquivo')}
        >
          <RefreshCw className="h-4 w-4" />
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={onDelete}
          disabled={deleteDisabled}
          data-testid={`button-delete-document-${doc.id}`}
        >
          <Trash2 className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

type TrailerAuditLogEntry = {
  id: string;
  action: string;
  entityType: string;
  entityId: string | null;
  details: any;
  ipAddress: string | null;
  timestamp: string;
  user: { id: string; username: string; email: string; role: string } | null;
};

function TrailerHistoryTab({ trailerId }: { trailerId: string }) {
  const { t } = useTranslation();

  const { data: logs, isLoading, isError } = useQuery<TrailerAuditLogEntry[]>({
    queryKey: ["/api/trailers", trailerId, "audit-logs"],
  });

  if (isLoading) {
    return (
      <div className="space-y-3" data-testid="history-loading">
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
      </div>
    );
  }

  if (isError) {
    return (
      <div
        className="p-4 rounded-md bg-destructive/10 text-destructive text-sm"
        data-testid="history-error"
      >
        {t('assets.history.loadError', 'Failed to load history.')}
      </div>
    );
  }

  if (!logs || logs.length === 0) {
    return (
      <div
        className="p-6 text-center text-sm text-muted-foreground border border-dashed rounded-md"
        data-testid="history-empty"
      >
        {t('assets.history.empty', 'No changes have been recorded for this asset yet.')}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div>
        <h3 className="font-semibold text-lg" data-testid="text-history-title">
          {t('assets.history.title', 'Edit History')}
        </h3>
        <p className="text-sm text-muted-foreground">
          {t('assets.history.description', 'Who changed this asset, when, and which fields were updated.')}
        </p>
      </div>

      <div className="space-y-3" data-testid="list-history-entries">
        {logs.map((entry) => (
          <HistoryEntry key={entry.id} entry={entry} />
        ))}
      </div>
    </div>
  );
}

function HistoryEntry({ entry }: { entry: TrailerAuditLogEntry }) {
  const { t } = useTranslation();
  const [showDetails, setShowDetails] = useState(false);

  // entry.user is null in two cases: (a) the originating user was deleted,
  // and (b) the audit log row was written without a userId (system jobs
  // such as the cron-driven invoice/payment generators). We can tell them
  // apart by looking at entry.userId — present-but-not-joined means the
  // user was deleted, missing means it was a system action.
  const userLabel = entry.user
    ? entry.user.username || entry.user.email
    : (entry as any).userId
      ? t('assets.history.unknownUser', 'Removed user')
      : t('assets.history.systemUser', 'System');

  const actionLabel = t(
    `assets.history.actions.${entry.action}`,
    entry.action.replace(/_/g, ' '),
  );

  const changedFields: string[] = Array.isArray(entry.details?.changedFields)
    ? entry.details.changedFields
    : [];

  let formattedTime = entry.timestamp;
  try {
    formattedTime = format(new Date(entry.timestamp), "dd/MM/yyyy HH:mm");
  } catch {
    /* fall back to raw string */
  }

  const hasDetailsPayload =
    entry.details && typeof entry.details === "object" && Object.keys(entry.details).length > 0;

  return (
    <div
      className="border rounded-md p-3 bg-muted/20 space-y-2"
      data-testid={`history-entry-${entry.id}`}
    >
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="flex items-start gap-2 min-w-0">
          <div className="mt-0.5 text-muted-foreground">
            <HistoryIcon className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <p
              className="font-medium text-sm"
              data-testid={`text-history-action-${entry.id}`}
            >
              {actionLabel}
            </p>
            <p className="text-xs text-muted-foreground flex items-center gap-1.5 mt-0.5">
              <UserIcon className="h-3 w-3" />
              <span data-testid={`text-history-user-${entry.id}`}>{userLabel}</span>
              {entry.user?.role && (
                <Badge variant="outline" className="text-[10px] px-1.5 py-0 h-4">
                  {entry.user.role}
                </Badge>
              )}
            </p>
          </div>
        </div>
        <div
          className="text-xs text-muted-foreground font-mono whitespace-nowrap"
          data-testid={`text-history-timestamp-${entry.id}`}
        >
          {formattedTime}
        </div>
      </div>

      <div className="text-xs">
        <span className="text-muted-foreground">
          {t('assets.history.changedFields', 'Changed fields')}:
        </span>{" "}
        {changedFields.length > 0 ? (
          <span className="flex flex-wrap gap-1 mt-1" data-testid={`list-history-fields-${entry.id}`}>
            {changedFields.map((field) => (
              <Badge key={field} variant="secondary" className="text-[10px]">
                {field}
              </Badge>
            ))}
          </span>
        ) : (
          <span className="text-muted-foreground italic">
            {t('assets.history.noFieldsChanged', 'No field details')}
          </span>
        )}
      </div>

      {hasDetailsPayload && (
        <Collapsible open={showDetails} onOpenChange={setShowDetails}>
          <CollapsibleTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="h-6 px-2 text-xs"
              data-testid={`button-toggle-history-details-${entry.id}`}
            >
              <ChevronDown
                className={`h-3 w-3 mr-1 transition-transform ${showDetails ? "rotate-180" : ""}`}
              />
              {showDetails
                ? t('assets.history.hideDetails', 'Hide details')
                : t('assets.history.showDetails', 'Show details')}
            </Button>
          </CollapsibleTrigger>
          <CollapsibleContent>
            <pre
              className="mt-2 p-2 rounded bg-background/60 border text-[11px] font-mono overflow-x-auto"
              data-testid={`text-history-details-${entry.id}`}
            >
              {JSON.stringify(entry.details, null, 2)}
            </pre>
          </CollapsibleContent>
        </Collapsible>
      )}
    </div>
  );
}
