import type { Tenant, Invoice } from '@shared/schema';

/**
 * Per-tenant payment methods exposed on an invoice. Generated by
 * buildPaymentMethods() from the tenant configuration. Methods that the
 * tenant has not configured are simply omitted from the list.
 *
 * All methods share a `reference` field equal to the invoice number so the
 * tenant can reconcile incoming ACH transfers against the invoice.
 *
 * Note: the `bankAgency` column on the tenant is reused semantically as the
 * ACH routing number for the US flow.
 */
export type PaymentMethodBank = {
  type: 'bank_transfer';
  bankName: string;
  routingNumber: string | null;
  account: string;
  accountHolder: string | null;
  accountType: string | null;
  amount: number;
  reference: string;
};

export type PaymentMethodStripe = {
  type: 'stripe';
  amount: number;
  reference: string;
  checkoutPath: string;
  publicPaymentUrl?: string;
};

export type PaymentMethod = PaymentMethodBank | PaymentMethodStripe;

type MinimalTenant = Pick<
  Tenant,
  | 'bankName'
  | 'bankAgency'
  | 'bankAccount'
  | 'bankAccountHolder'
  | 'bankAccountType'
> | null
  | undefined;

type MinimalInvoice = Pick<Invoice, 'id' | 'invoiceNumber' | 'amount'>;

export function buildPaymentMethods(
  tenant: MinimalTenant,
  invoice: MinimalInvoice,
  options?: { publicPaymentUrl?: string | null },
): PaymentMethod[] {
  const methods: PaymentMethod[] = [];
  const amount = parseFloat(invoice.amount?.toString() ?? '0');
  const reference = invoice.invoiceNumber;

  const bankName = tenant?.bankName?.trim();
  const bankAccount = tenant?.bankAccount?.trim();
  if (bankName && bankAccount) {
    methods.push({
      type: 'bank_transfer',
      bankName,
      routingNumber: tenant?.bankAgency?.trim() || null,
      account: bankAccount,
      accountHolder: tenant?.bankAccountHolder?.trim() || null,
      accountType: tenant?.bankAccountType?.trim() || null,
      amount,
      reference,
    });
  }

  // Stripe is always available when configured at the platform level. The
  // checkout page itself decides whether Stripe is configured; we just emit
  // the link so the UI can show the tab.
  methods.push({
    type: 'stripe',
    amount,
    reference,
    checkoutPath: `/checkout/invoice?invoiceId=${invoice.id}`,
    publicPaymentUrl: options?.publicPaymentUrl ?? undefined,
  });

  return methods;
}

/**
 * Render the payment methods as plain text lines for the PDF. Mirrors the
 * order returned by buildPaymentMethods() so the PDF, JSON, and UI all stay
 * consistent.
 */
export function paymentMethodsToInstructionLines(
  methods: PaymentMethod[],
): string[] {
  if (methods.length === 0) {
    return ['No payment method configured. Please contact the issuer.'];
  }

  const lines: string[] = [];

  methods.forEach((method, index) => {
    if (index > 0) lines.push('');

    if (method.type === 'bank_transfer') {
      lines.push('Bank Transfer (ACH)');
      lines.push(`Bank: ${method.bankName}`);
      if (method.routingNumber) lines.push(`Routing Number: ${method.routingNumber}`);
      lines.push(`Account: ${method.account}`);
      if (method.accountHolder) lines.push(`Account Holder: ${method.accountHolder}`);
      if (method.accountType) {
        lines.push(`Type: ${method.accountType === 'checking' ? 'Checking' : method.accountType === 'savings' ? 'Savings' : method.accountType}`);
      }
      lines.push(`Amount: ${formatAmount(method.amount)}`);
      lines.push(`Reference: ${method.reference}`);
    } else if (method.type === 'stripe') {
      lines.push('Credit Card (Online)');
      lines.push(`Amount: ${formatAmount(method.amount)}`);
      lines.push(`Reference: ${method.reference}`);
      if (method.publicPaymentUrl) {
        lines.push(`Pay online at: ${method.publicPaymentUrl}`);
      } else {
        lines.push('Pay online via the invoice link in your portal.');
      }
    }
  });

  return lines;
}

function formatAmount(amount: number): string {
  return amount.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}
