import type { Tenant, Invoice } from '@shared/schema';

/**
 * Per-tenant payment methods exposed on an invoice. Generated by
 * buildPaymentMethods() from the tenant configuration. Methods that the
 * tenant has not configured are simply omitted from the list.
 *
 * All methods share a `reference` field equal to the invoice number so the
 * tenant can reconcile incoming PIX/bank transfers against the invoice.
 */
export type PaymentMethodPix = {
  type: 'pix';
  pixKey: string;
  beneficiary: string | null;
  amount: number;
  reference: string;
};

export type PaymentMethodBank = {
  type: 'bank_transfer';
  bankName: string;
  agency: string | null;
  account: string;
  accountHolder: string | null;
  accountType: string | null;
  amount: number;
  reference: string;
};

export type PaymentMethodStripe = {
  type: 'stripe';
  amount: number;
  reference: string;
  checkoutPath: string;
};

export type PaymentMethod =
  | PaymentMethodPix
  | PaymentMethodBank
  | PaymentMethodStripe;

type MinimalTenant = Pick<
  Tenant,
  | 'pixKey'
  | 'pixBeneficiary'
  | 'bankName'
  | 'bankAgency'
  | 'bankAccount'
  | 'bankAccountHolder'
  | 'bankAccountType'
> | null
  | undefined;

type MinimalInvoice = Pick<Invoice, 'id' | 'invoiceNumber' | 'amount'>;

export function buildPaymentMethods(
  tenant: MinimalTenant,
  invoice: MinimalInvoice,
): PaymentMethod[] {
  const methods: PaymentMethod[] = [];
  const amount = parseFloat(invoice.amount?.toString() ?? '0');
  const reference = invoice.invoiceNumber;

  const pixKey = tenant?.pixKey?.trim();
  if (pixKey) {
    methods.push({
      type: 'pix',
      pixKey,
      beneficiary: tenant?.pixBeneficiary?.trim() || null,
      amount,
      reference,
    });
  }

  const bankName = tenant?.bankName?.trim();
  const bankAccount = tenant?.bankAccount?.trim();
  if (bankName && bankAccount) {
    methods.push({
      type: 'bank_transfer',
      bankName,
      agency: tenant?.bankAgency?.trim() || null,
      account: bankAccount,
      accountHolder: tenant?.bankAccountHolder?.trim() || null,
      accountType: tenant?.bankAccountType?.trim() || null,
      amount,
      reference,
    });
  }

  // Stripe is always available when configured at the platform level. The
  // checkout page itself decides whether Stripe is configured; we just emit
  // the link so the UI can show the tab.
  methods.push({
    type: 'stripe',
    amount,
    reference,
    checkoutPath: `/checkout/invoice?invoiceId=${invoice.id}`,
  });

  return methods;
}

/**
 * Render the payment methods as plain text lines for the PDF. Mirrors the
 * order returned by buildPaymentMethods() so the PDF, JSON, and UI all stay
 * consistent.
 */
export function paymentMethodsToInstructionLines(
  methods: PaymentMethod[],
): string[] {
  if (methods.length === 0) {
    return ['No payment methods configured. Please contact the issuer.'];
  }

  const lines: string[] = [];

  methods.forEach((method, index) => {
    if (index > 0) lines.push('');

    if (method.type === 'pix') {
      lines.push('PIX');
      lines.push(`Key: ${method.pixKey}`);
      if (method.beneficiary) lines.push(`Beneficiary: ${method.beneficiary}`);
      lines.push(`Amount: ${formatAmount(method.amount)}`);
      lines.push(`Reference: ${method.reference}`);
    } else if (method.type === 'bank_transfer') {
      lines.push('Bank Transfer');
      lines.push(`Bank: ${method.bankName}`);
      if (method.agency) lines.push(`Agency: ${method.agency}`);
      lines.push(`Account: ${method.account}`);
      if (method.accountHolder) lines.push(`Holder: ${method.accountHolder}`);
      if (method.accountType) lines.push(`Type: ${method.accountType}`);
      lines.push(`Amount: ${formatAmount(method.amount)}`);
      lines.push(`Reference: ${method.reference}`);
    } else if (method.type === 'stripe') {
      lines.push('Card (Online)');
      lines.push(`Amount: ${formatAmount(method.amount)}`);
      lines.push(`Reference: ${method.reference}`);
      lines.push('Pay online via the invoice link in your portal.');
    }
  });

  return lines;
}

function formatAmount(amount: number): string {
  return `$${amount.toFixed(2)}`;
}
